/**
 * The Vigía mark: a V (the lookout's field of view) facing an arc of eight points (the arc of stars on the
 * Venezuelan flag, and blips on a watch screen). Geometry generated by scripts/brand-gen.py.
 *
 * Motion: on first paint the V draws and the points light up in sequence. After that it is still, and it only
 * moves when data arrives (`pulse` changes): a sweep runs across the points. Reduced motion: static.
 *
 * <LiveMark> (the header's) makes the points a real meter: of the eight, as many are lit as the share of usable
 * feeds that are live (95 of 97 → 8, 85 of 97 → 7); the rest are grey. It blips only when a feed brings a newer
 * observation, not on every fetch.
 */

import { useEffect, useState } from "preact/hooks";
import { health } from "../lib/data.ts";
import { feedCounts } from "../lib/fresh.ts";
import { t } from "../lib/i18n.ts";
import { WORDMARK_ACCENT, WORDMARK_LETTERS, WORDMARK_VIEWBOX } from "./wordmark-paths.ts";

const CX = 32;
const CY = 53;
const DOTS = Array.from({ length: 8 }, (_, i) => {
	const deg = -33 + (i * 66) / 7;
	const a = (deg * Math.PI) / 180;
	return { x: CX + 43 * Math.sin(a), y: CY - 43 * Math.cos(a) };
});
const beam = (deg: number) => {
	const a = (deg * Math.PI) / 180;
	return `${(CX + 33 * Math.sin(a)).toFixed(2)} ${(CY - 33 * Math.cos(a)).toFixed(2)}`;
};
const V_PATH = `M${beam(-30)} L${CX} ${CY} L${beam(30)}`;

export function Mark({
	size = 28,
	pulse = 0,
	intro = true,
	lit = DOTS.length,
	label,
}: {
	size?: number;
	pulse?: number;
	intro?: boolean;
	/** How many points are lit (the rest grey), left to right. */
	lit?: number;
	/** Accessible reading of the meter; without it the mark is decorative. */
	label?: string;
}) {
	return (
		<svg
			class={`mark${intro ? " mark--intro" : ""}`}
			viewBox="0 0 64 64"
			width={size}
			height={size}
			focusable="false"
			role={label ? "img" : undefined}
			aria-label={label}
			aria-hidden={label ? undefined : "true"}
		>
			{label ? <title>{label}</title> : null}
			<path class="mark__v" d={V_PATH} pathLength={1} />
			<g class="mark__dots" key={pulse}>
				{DOTS.map((d, i) => (
					<circle
						cx={d.x.toFixed(2)}
						cy={d.y.toFixed(2)}
						r="2.5"
						style={{ "--i": i }}
						class={i < lit ? undefined : "is-off"}
					/>
				))}
			</g>
		</svg>
	);
}

/** Share of usable feeds that are live, as lit points of the mark (never 0 of 8 while one feed is live). */
export function litPoints(live: number, usable: number, points = DOTS.length): number {
	if (usable <= 0) return 0;
	const lit = Math.round((points * live) / usable);
	return live > 0 ? Math.max(1, lit) : 0;
}

/** The header mark: a meter of live feeds that blips when newer data lands. */
export function LiveMark({ size = 30 }: { size?: number }) {
	const [pulse, setPulse] = useState(0);
	useEffect(() => {
		let last = "";
		return health.subscribe((feeds) => {
			const key = feeds.map((f) => f.newestObservedAt ?? 0).join(",");
			if (last && key !== last) setPulse((p) => p + 1);
			last = key;
		});
	}, []);
	// The same count as the status bar and the header (lib/fresh.ts feedCounts).
	const { live, enabled } = feedCounts(health.value);
	return (
		<Mark
			size={size}
			pulse={pulse}
			intro={pulse === 0}
			lit={health.value.length ? litPoints(live, enabled) : DOTS.length}
			label={
				health.value.length
					? t(`Vigía: ${live} de ${enabled} fuentes al día`, `Vigía: ${live} of ${enabled} feeds current`)
					: "Vigía"
			}
		/>
	);
}

export function Wordmark({ height = 16 }: { height?: number }) {
	return (
		<svg
			class="wordmark"
			viewBox={WORDMARK_VIEWBOX}
			height={height}
			width={(height * 3807) / 900}
			role="img"
			aria-label="Vigía"
		>
			<g class="wordmark__letters">
				{WORDMARK_LETTERS.map((d) => (
					<path d={d} />
				))}
			</g>
			<path class="wordmark__accent" d={WORDMARK_ACCENT} />
		</svg>
	);
}
