/**
 * The commercial airlines whose flights may be listed (by flight number), by ICAO designator, checked by hand
 * (2026-09-29) against the designators in the VRS route database's Venezuelan routes (CC0) and the airlines that
 * cross the region. It is an allowlist: a designator not here is never listed, only counted, because a three-letter
 * operator code alone cannot tell an airline from a business-jet operator, a charter carrying private people, or a
 * state or military transport (RCH, SAM, CNV…). Designators get reassigned over the years, so an old public list
 * (OpenFlights, 2014) is not used.
 */
export const AIRLINES: Readonly<Record<string, string>> = {
	// Venezuelan
	VCV: "Conviasa",
	RUC: "Rutaca",
	ROI: "Avior Airlines",
	LER: "Laser Airlines",
	OCA: "Aserca Airlines",
	BBR: "Santa Bárbara Airlines",
	VNE: "Venezolana",
	ETR: "Estelar",
	TIW: "Transcarga",
	// Region and beyond
	CMP: "Copa Airlines",
	RPB: "AeroRepública (Wingo)",
	AVA: "Avianca",
	LAN: "LATAM",
	TAM: "LATAM Brasil",
	GLO: "Gol",
	AZU: "Azul",
	ARG: "Aerolíneas Argentinas",
	AMX: "Aeroméxico",
	CUB: "Cubana de Aviación",
	BWA: "Caribbean Airlines",
	DWI: "Arajet",
	SKU: "Sky Airline",
	TAP: "TAP Air Portugal",
	IBE: "Iberia",
	AEA: "Air Europa",
	PUE: "Plus Ultra",
	THY: "Turkish Airlines",
	AFR: "Air France",
	KLM: "KLM",
	DLH: "Lufthansa",
	BAW: "British Airways",
	SWR: "Swiss",
	EDW: "Edelweiss",
	ITY: "ITA Airways",
	AAL: "American Airlines",
	DAL: "Delta Air Lines",
	UAL: "United Airlines",
	JBU: "JetBlue",
	NKS: "Spirit Airlines",
	SWA: "Southwest Airlines",
	ACA: "Air Canada",
	ROU: "Air Canada Rouge",
	WJA: "WestJet",
	TSC: "Air Transat",
	IBS: "Iberia Express",
	VOI: "Volaris",
	FFT: "Frontier Airlines",
	AAY: "Allegiant Air",
	LPE: "LATAM Perú",
	TAI: "Avianca El Salvador (TACA)",
	LRC: "Avianca Costa Rica (LACSA)",
	NSE: "SATENA",
	// Cargo airlines
	FDX: "FedEx Express",
	UPS: "UPS Airlines",
	GTI: "Atlas Air",
	CKS: "Kalitta Air",
	AJT: "Amerijet International",
	CLX: "Cargolux",
	ABX: "ABX Air",
	DAE: "DHL Aero Expreso",
	LCO: "LATAM Cargo",
};
