/**
 * Venezuelan and international outlet feeds, verified live on 2026-09-24.
 * region: "national", an ISO state code for regional outlets, "diaspora", or "international".
 * stance is descriptive, one neutral word, shown next to the outlet name so readers can weigh it.
 * Intervals follow each feed's measured volume (items per day).
 */
import { TELEGRAM_CHANNELS } from "../telegram/channels.ts";
import type { OutletSpec } from "./factory.ts";

const MIN = 60_000;

/**
 * The host's robots.txt excludes this feed for automated agents (YouTube's /feeds/videos.xml, and four outlets,
 * often through an SEO template). On by default since 2026-09-25 by the project's decision: read at
 * the entry's own interval with the per-host pacing of every feed, never faster, and the user can turn it off.
 */
export const ROBOTS_NOTE = {
	es: "Su robots.txt excluye lectores automáticos; Vigía lo lee a ritmo bajo por decisión del proyecto.",
	en: "Its robots.txt excludes automated readers; Vigía reads it at a low rate by the project's decision.",
} as const;

export const OUTLETS: readonly OutletSpec[] = [
	{
		id: "2001online",
		name: "2001online",
		url: "https://www.2001online.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.2001online.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "alba-ciudad",
		name: "Alba Ciudad",
		url: "https://albaciudad.org/feed/",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://albaciudad.org/",
		intervalMs: 60 * MIN,
	},
	{
		id: "analitica",
		name: "Analítica",
		url: "https://www.analitica.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.analitica.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "aporrea",
		name: "Aporrea",
		url: "https://www.aporrea.org/rssfeed",
		kind: "rss",
		region: "national",
		stance: "partisan",
		homepage: "https://www.aporrea.org/",
		intervalMs: 10 * MIN,
	},
	{
		id: "armando-info",
		name: "Armando.info",
		url: "https://armando.info/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://armando.info/",
		intervalMs: 180 * MIN,
	},
	{
		id: "caraota-digital",
		name: "Caraota Digital",
		url: "https://www.caraotadigital.net/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.caraotadigital.net/",
		intervalMs: 10 * MIN,
	},
	{
		id: "contrapunto",
		name: "Contrapunto",
		url: "https://contrapunto.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://contrapunto.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "cronica-uno",
		name: "Crónica.Uno",
		url: "https://cronica.uno/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://cronica.uno/",
		intervalMs: 60 * MIN,
	},
	{
		id: "descifrado",
		name: "Descifrado",
		url: "https://www.descifrado.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://www.descifrado.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "el-diario",
		name: "El Diario",
		url: "https://eldiario.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://eldiario.com/",
		intervalMs: 20 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "el-estimulo",
		name: "El Estímulo",
		url: "https://elestimulo.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://elestimulo.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "el-pitazo",
		name: "El Pitazo",
		url: "https://elpitazo.net/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://elpitazo.net/",
		intervalMs: 10 * MIN,
	},
	{
		id: "el-pitazo-regiones",
		name: "El Pitazo Regiones",
		url: "https://elpitazo.net/category/regiones/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://elpitazo.net/",
		intervalMs: 20 * MIN,
		publisher: "el-pitazo",
	},
	{
		id: "espacio-publico",
		name: "Espacio Público",
		url: "https://espaciopublico.ong/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://espaciopublico.ong/",
		intervalMs: 60 * MIN,
		genre: "rights",
		note: ROBOTS_NOTE,
	},
	{
		id: "foro-penal",
		name: "Foro Penal",
		url: "https://foropenal.com/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://foropenal.com/",
		intervalMs: 60 * MIN,
		genre: "rights",
	},
	{
		id: "globovision",
		name: "Globovisión",
		url: "https://www.globovision.com/rss.xml",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.globovision.com/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "impacto-ve",
		name: "Impacto Venezuela",
		url: "https://backendimpactove.eleco.com.ar/feed-notes",
		kind: "atom",
		region: "national",
		stance: "commercial",
		homepage: "https://backendimpactove.eleco.com.ar/",
		intervalMs: 20 * MIN,
	},
	{
		id: "informe21",
		name: "Informe21",
		url: "https://www.informe21.com/blog-feed.xml",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.informe21.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "la-gran-aldea",
		name: "La Gran Aldea",
		url: "https://lagranaldea.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://lagranaldea.com/",
		intervalMs: 180 * MIN,
	},
	{
		id: "mision-verdad",
		name: "Misión Verdad",
		url: "https://misionverdad.com/rss.xml",
		kind: "rss",
		region: "national",
		stance: "partisan",
		homepage: "https://misionverdad.com/",
		intervalMs: 180 * MIN,
	},
	{
		id: "monitoreamos",
		name: "Monitoreamos",
		url: "https://monitoreamos.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://monitoreamos.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "observatorio-dd-hh",
		name: "Acceso a la Justicia",
		url: "https://accesoalajusticia.org/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://accesoalajusticia.org/",
		intervalMs: 60 * MIN,
		genre: "rights",
		note: ROBOTS_NOTE,
	},
	{
		id: "radio-fe-y-alegria",
		name: "Radio Fe y Alegría Noticias",
		url: "https://www.radiofeyalegrianoticias.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://www.radiofeyalegrianoticias.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "reporte-confidencial",
		name: "Reporte Confidencial",
		url: "https://reporteconfidencial.info/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://reporteconfidencial.info/",
		intervalMs: 20 * MIN,
	},
	{
		id: "runrunes",
		name: "Runrunes",
		url: "https://runrun.es/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://runrun.es/",
		intervalMs: 20 * MIN,
	},
	{
		id: "tal-cual",
		name: "Tal Cual",
		url: "https://talcualdigital.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://talcualdigital.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "televen",
		name: "Televen",
		url: "https://televen.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://televen.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "tves",
		name: "TVes",
		url: "https://tves.gob.ve/feed/",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://tves.gob.ve/",
		intervalMs: 10 * MIN,
	},
	{
		id: "vtv",
		name: "VTV",
		url: "https://vtv.com.ve/feed/",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://vtv.com.ve/",
		intervalMs: 10 * MIN,
	},
	{
		id: "yt-efecto-cocuyo",
		name: "Efecto Cocuyo (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCL1TMK6T2MpnLUk9mpvMdKQ",
		kind: "youtube",
		region: "national",
		stance: "independent",
		homepage: "https://www.youtube.com/channel/UCL1TMK6T2MpnLUk9mpvMdKQ",
		intervalMs: 60 * MIN,
		publisher: "efecto-cocuyo",
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-el-estimulo",
		name: "El Estímulo (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC2V_WrmWpQ7jIwAWQprlIfw",
		kind: "youtube",
		region: "national",
		stance: "independent",
		homepage: "https://www.youtube.com/channel/UC2V_WrmWpQ7jIwAWQprlIfw",
		intervalMs: 60 * MIN,
		publisher: "el-estimulo",
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-el-pitazo",
		name: "El Pitazo (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCehmligXGWQbJGQF12cK9UA",
		kind: "youtube",
		region: "national",
		stance: "independent",
		homepage: "https://www.youtube.com/channel/UCehmligXGWQbJGQF12cK9UA",
		intervalMs: 60 * MIN,
		publisher: "el-pitazo",
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-globovision",
		name: "Globovisión en Vivo (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC0nGYg5JpX7tIeQw_-DQTLw",
		kind: "youtube",
		region: "national",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UC0nGYg5JpX7tIeQw_-DQTLw",
		intervalMs: 10 * MIN,
		publisher: "globovision",
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-televen",
		name: "Televen (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPxs1siPSF6YKGtKP_Zyvtw",
		kind: "youtube",
		region: "national",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UCPxs1siPSF6YKGtKP_Zyvtw",
		intervalMs: 20 * MIN,
		publisher: "televen",
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-vtv",
		name: "VTV (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_8sCVycu3FXidPNoZwOHqA",
		kind: "youtube",
		region: "national",
		stance: "state",
		homepage: "https://www.youtube.com/channel/UC_8sCVycu3FXidPNoZwOHqA",
		intervalMs: 10 * MIN,
		publisher: "vtv",
		note: ROBOTS_NOTE,
	},
	{
		id: "el-tiempo-anz",
		name: "El Tiempo (Anzoátegui)",
		url: "https://eltiempo.com.ve/feed/",
		kind: "rss",
		region: "VE-B",
		stance: "commercial",
		homepage: "https://eltiempo.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "el-tiempo-ve",
		name: "El Tiempo (eltiempove)",
		url: "https://eltiempove.com/feed/",
		kind: "rss",
		region: "VE-B",
		stance: "commercial",
		homepage: "https://eltiempove.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "el-clarin",
		name: "El Clarín (Aragua)",
		url: "https://elclarinweb.com/feed/",
		kind: "rss",
		region: "VE-D",
		stance: "commercial",
		homepage: "https://elclarinweb.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "el-siglo",
		name: "El Siglo (Aragua)",
		url: "https://elsiglo.com.ve/feed/",
		kind: "rss",
		region: "VE-D",
		stance: "commercial",
		homepage: "https://elsiglo.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "primicia",
		name: "Primicia (Bolívar)",
		url: "https://primicia.com.ve/feed/",
		kind: "rss",
		region: "VE-F",
		stance: "commercial",
		homepage: "https://primicia.com.ve/",
		intervalMs: 10 * MIN,
	},
	{
		id: "notitarde",
		name: "Notitarde (Carabobo)",
		url: "https://www.notitarde.com.ve/rss.php",
		kind: "rss",
		region: "VE-G",
		stance: "commercial",
		homepage: "https://www.notitarde.com.ve/",
		intervalMs: 60 * MIN,
	},
	{
		id: "caracas-chronicles",
		name: "Caracas Chronicles (EN)",
		url: "https://www.caracaschronicles.com/feed/",
		kind: "rss",
		region: "diaspora",
		stance: "independent",
		homepage: "https://www.caracaschronicles.com/",
		intervalMs: 60 * MIN,
		lang: "en",
	},
	{
		id: "diario-las-americas",
		name: "Diario Las Américas",
		url: "https://www.diariolasamericas.com/rss/america-latina.xml",
		kind: "rss",
		region: "diaspora",
		stance: "commercial",
		homepage: "https://www.diariolasamericas.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "yt-vpitv",
		name: "VPItv (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVFiIRuxJ2GmJLUkHmlmj4w",
		kind: "youtube",
		region: "diaspora",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UCVFiIRuxJ2GmJLUkHmlmj4w",
		intervalMs: 10 * MIN,
		publisher: "vpitv",
		note: ROBOTS_NOTE,
	},
	{
		id: "nuevo-dia",
		name: "Nuevo Día (Falcón)",
		url: "https://nuevodia.com.ve/feed/",
		kind: "rss",
		region: "VE-I",
		stance: "commercial",
		homepage: "https://nuevodia.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "abc-es",
		name: "ABC (Spain) Internacional",
		url: "https://www.abc.es/rss/2.0/internacional/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.abc.es/",
		intervalMs: 20 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "aljazeera-es",
		name: "Al Jazeera (EN) all",
		url: "https://www.aljazeera.com/xml/rss/all.xml",
		kind: "rss",
		region: "international",
		stance: "state-funded",
		homepage: "https://www.aljazeera.com/",
		intervalMs: 10 * MIN,
		onlyVenezuela: true,
		lang: "en",
	},
	{
		id: "bbc-mundo",
		name: "BBC Mundo",
		url: "https://feeds.bbci.co.uk/mundo/rss.xml",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://feeds.bbci.co.uk/",
		intervalMs: 60 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "dw-es",
		name: "DW Español",
		url: "https://rss.dw.com/rdf/rss-sp-all",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://rss.dw.com/",
		intervalMs: 20 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "dw-es-top",
		name: "DW Español top",
		url: "https://rss.dw.com/rdf/rss-sp-top",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://rss.dw.com/",
		intervalMs: 20 * MIN,
		onlyVenezuela: true,
		publisher: "dw-es",
	},
	{
		id: "el-mundo-es",
		name: "El Mundo (Spain) América",
		url: "https://e00-elmundo.uecdn.es/elmundo/rss/internacional.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://e00-elmundo.uecdn.es/",
		intervalMs: 20 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "el-tiempo-co",
		name: "El Tiempo (Colombia) mundo",
		url: "https://www.eltiempo.com/rss/mundo_latinoamerica.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.eltiempo.com/",
		intervalMs: 60 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "elpais-america",
		name: "El País América",
		url: "https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/america",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://feeds.elpais.com/",
		intervalMs: 20 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "elpais-venezuela",
		name: "El País tag Venezuela",
		url: "https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/tag/venezuela_a",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://feeds.elpais.com/",
		intervalMs: 60 * MIN,
		publisher: "elpais-america",
	},
	{
		id: "euronews-es",
		name: "Euronews Español",
		url: "https://es.euronews.com/rss",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://es.euronews.com/",
		intervalMs: 10 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "europa-press-latam",
		name: "Europa Press Latam",
		url: "https://www.europapress.es/rss/rss.aspx?ch=00280",
		kind: "rss",
		region: "international",
		stance: "agency",
		homepage: "https://www.europapress.es/",
		intervalMs: 20 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "france24-es",
		name: "France 24 Español",
		url: "https://www.france24.com/es/tag/venezuela/rss",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.france24.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "france24-latam",
		name: "France 24 América Latina",
		url: "https://www.france24.com/es/am%C3%A9rica-latina/rss",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.france24.com/",
		intervalMs: 60 * MIN,
		onlyVenezuela: true,
		publisher: "france24-es",
	},
	{
		id: "guardian-ve",
		name: "The Guardian: Venezuela (EN)",
		url: "https://www.theguardian.com/world/venezuela/rss",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.theguardian.com/",
		intervalMs: 60 * MIN,
		lang: "en",
	},
	{
		id: "infobae-venezuela",
		name: "Infobae Venezuela",
		url: "https://www.infobae.com/arc/outboundfeeds/rss/category/venezuela/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.infobae.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "nyt-es",
		name: "NYT (EN) Americas",
		url: "https://rss.nytimes.com/services/xml/rss/nyt/Americas.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://rss.nytimes.com/",
		intervalMs: 20 * MIN,
		onlyVenezuela: true,
		lang: "en",
	},
	{
		id: "rfi-es",
		name: "RFI Español",
		url: "https://www.rfi.fr/es/am%C3%A9ricas/rss",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.rfi.fr/",
		intervalMs: 60 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "telesur",
		name: "teleSUR",
		url: "https://www.telesurtv.net/feed/",
		kind: "rss",
		region: "international",
		stance: "state",
		homepage: "https://www.telesurtv.net/",
		intervalMs: 10 * MIN,
		onlyVenezuela: true,
	},
	{
		id: "yt-cnn-es",
		name: "CNN en Español (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC_lEiu6917IJz03TnntWUaQ",
		kind: "youtube",
		region: "international",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UC_lEiu6917IJz03TnntWUaQ",
		intervalMs: 10 * MIN,
		onlyVenezuela: true,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-ntn24",
		name: "NTN24 (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCEJs1fTF3KszRJGxJY14VrA",
		kind: "youtube",
		region: "international",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UCEJs1fTF3KszRJGxJY14VrA",
		intervalMs: 10 * MIN,
		onlyVenezuela: true,
		note: ROBOTS_NOTE,
	},
	{
		id: "el-impulso",
		name: "El Impulso (Lara)",
		url: "https://www.elimpulso.com/feed/",
		kind: "rss",
		region: "VE-K",
		stance: "independent",
		homepage: "https://www.elimpulso.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "el-informador",
		name: "El Informador (Lara)",
		url: "https://elinformadorve.com/category/venezuela/feed/",
		kind: "rss",
		region: "VE-K",
		stance: "commercial",
		homepage: "https://elinformadorve.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "la-prensa-lara",
		name: "La Prensa de Lara",
		url: "https://www.laprensalara.com.ve/feed/",
		kind: "rss",
		region: "VE-K",
		stance: "commercial",
		homepage: "https://www.laprensalara.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "verdad-monagas",
		name: "La Verdad de Monagas",
		url: "https://laverdaddemonagas.com/feed/",
		kind: "rss",
		region: "VE-N",
		stance: "commercial",
		homepage: "https://laverdaddemonagas.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "la-nacion",
		name: "La Nación (Táchira)",
		url: "https://lanacionweb.com/feed/",
		kind: "rss",
		region: "VE-S",
		stance: "commercial",
		homepage: "https://lanacionweb.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "diario-el-tiempo-trujillo",
		name: "Diario El Tiempo (Trujillo)",
		url: "https://diarioeltiempo.com.ve/feed/",
		kind: "rss",
		region: "VE-T",
		stance: "commercial",
		homepage: "https://diarioeltiempo.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "la-verdad",
		name: "La Verdad (Zulia)",
		url: "https://laverdad.com/feed/",
		kind: "rss",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://laverdad.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "noticia-al-dia",
		name: "Noticia al Día (Zulia)",
		url: "https://noticialdia.com/feed/",
		kind: "rss",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://noticialdia.com/",
		intervalMs: 10 * MIN,
	},
	// Venezuelan national outlets, independent and investigative sites (wave of 2026-09-24).
	{
		id: "connectas-ve",
		name: "Connectas (Venezuela tag)",
		url: "https://www.connectas.org/tag/venezuela/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://www.connectas.org/",
		intervalMs: 180 * MIN,
	},
	{
		id: "efecto-cocuyo",
		name: "Efecto Cocuyo",
		url: "https://efectococuyo.com/feed/",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://efectococuyo.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "el-politico",
		name: "El Político",
		url: "https://elpolitico.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://elpolitico.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "frecuencia-noticias",
		name: "Frecuencia Noticias",
		url: "https://www.frecuencianoticias.com/feeds/posts/default",
		kind: "atom",
		region: "national",
		stance: "commercial",
		homepage: "https://www.frecuencianoticias.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "infodio",
		name: "Infodio",
		url: "https://infodio.com/rss.xml",
		kind: "rss",
		region: "national",
		stance: "independent",
		homepage: "https://infodio.com/",
		intervalMs: 180 * MIN,
	},
	{
		id: "la-razon-ve",
		name: "La Razón",
		url: "https://larazon.net/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://larazon.net/",
		intervalMs: 180 * MIN,
	},
	{
		id: "noticias-ahora",
		name: "Noticias Ahora",
		url: "https://noticias-ahora.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.noticias-ahora.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "noticias-al-dia-y-a-la-hora",
		name: "Noticias al Día y a la Hora",
		url: "https://noticiasaldiayalahora.co/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.noticiasaldiayalahora.co/",
		intervalMs: 10 * MIN,
	},
	{
		id: "notifalcon",
		name: "Notifalcon",
		url: "https://notifalcon.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.notifalcon.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "radio-america-ve",
		name: "Radio América VE",
		url: "https://www.radioamericave.com/feeds/posts/default",
		kind: "atom",
		region: "national",
		stance: "commercial",
		homepage: "https://www.radioamericave.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "suresnoticia",
		name: "Suresnoticia",
		url: "https://suresnoticia.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://www.suresnoticia.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "vpitv",
		name: "VPItv",
		url: "https://vpitv.com/feed/",
		kind: "rss",
		region: "national",
		stance: "commercial",
		homepage: "https://vpitv.com/",
		intervalMs: 180 * MIN,
	},
	// Venezuelan state media and official press sites (stance "state"; genre "official" for government bodies), pro-government and party media.
	{
		id: "gob-anzoategui",
		name: "Gobernación de Anzoátegui",
		url: "https://anzoategui.gob.ve/feed/",
		kind: "rss",
		region: "VE-B",
		stance: "state",
		homepage: "https://anzoategui.gob.ve/",
		genre: "official",
		intervalMs: 180 * MIN,
	},
	{
		id: "gob-guarico",
		name: "Gobernación de Guárico",
		url: "https://guarico.gob.ve/feed/",
		kind: "rss",
		region: "VE-J",
		stance: "state",
		homepage: "https://guarico.gob.ve/",
		genre: "official",
		intervalMs: 10 * MIN,
	},
	{
		id: "gob-lara",
		name: "Gobernación de Lara",
		url: "https://lara.gob.ve/feed/",
		kind: "rss",
		region: "VE-K",
		stance: "state",
		homepage: "https://lara.gob.ve/",
		genre: "official",
		intervalMs: 180 * MIN,
	},
	{
		id: "cuatro-f",
		name: "Cuatro F",
		url: "https://cuatrof.net/feed/",
		kind: "rss",
		region: "national",
		stance: "partisan",
		homepage: "https://cuatrof.net/",
		intervalMs: 60 * MIN,
	},
	{
		id: "mindefensa",
		name: "Ministerio de Defensa",
		url: "https://www.mindefensa.gob.ve/?feed=rss2",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://www.mindefensa.gob.ve/",
		genre: "official",
		intervalMs: 180 * MIN,
	},
	{
		id: "mpps",
		name: "Ministerio de Salud",
		url: "https://mpps.gob.ve/feed/",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://mpps.gob.ve/",
		genre: "official",
		intervalMs: 20 * MIN,
	},
	{
		id: "orinoco-tribune",
		name: "Orinoco Tribune",
		url: "https://orinocotribune.com/feed/",
		kind: "rss",
		region: "national",
		stance: "state-aligned",
		homepage: "https://orinocotribune.com/",
		lang: "en",
		intervalMs: 60 * MIN,
	},
	{
		id: "radio-mundial",
		name: "Radio Mundial YVKE",
		url: "https://radiomundial.com.ve/feed/",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://radiomundial.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "rnv",
		name: "Radio Nacional de Venezuela",
		url: "https://rnv.gob.ve/feed/",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://rnv.gob.ve/",
		intervalMs: 10 * MIN,
	},
	{
		id: "sundde",
		name: "SUNDDE",
		url: "https://www.sundde.gob.ve/?feed=rss2",
		kind: "rss",
		region: "national",
		stance: "state",
		homepage: "https://www.sundde.gob.ve/",
		genre: "official",
		intervalMs: 180 * MIN,
	},
	{
		id: "venezuelanalysis",
		name: "Venezuelanalysis",
		url: "https://venezuelanalysis.com/feed/",
		kind: "rss",
		region: "national",
		stance: "state-aligned",
		homepage: "https://venezuelanalysis.com/",
		lang: "en",
		intervalMs: 180 * MIN,
	},
	// Civil society: rights monitors, NGOs, professional and trade bodies.
	{
		id: "aula-abierta",
		name: "Aula Abierta",
		url: "https://aulaabiertalatinoamerica.org/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://aulaabiertalatinoamerica.org/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "cecodap",
		name: "Cecodap",
		url: "https://cecodap.org/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://cecodap.org/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "cepaz",
		name: "Cepaz",
		url: "https://cepaz.org/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://cepaz.org/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "cnp",
		name: "Colegio Nacional de Periodistas",
		url: "https://cnpven.org/feed/",
		kind: "rss",
		region: "national",
		stance: "trade-body",
		homepage: "https://cnpven.org/",
		intervalMs: 180 * MIN,
	},
	{
		id: "conindustria",
		name: "Conindustria",
		url: "https://www.conindustria.org/feed/",
		kind: "rss",
		region: "national",
		stance: "trade-body",
		homepage: "https://conindustria.org/",
		intervalMs: 180 * MIN,
	},
	{
		id: "caritas",
		name: "Cáritas de Venezuela",
		url: "https://caritasvenezuela.org/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://caritasvenezuela.org/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "fedeagro",
		name: "Fedeagro",
		url: "https://fedeagro.org/feed/",
		kind: "rss",
		region: "national",
		stance: "trade-body",
		homepage: "https://fedeagro.org/",
		intervalMs: 180 * MIN,
	},
	{
		id: "fedecamaras",
		name: "Fedecámaras",
		url: "https://fedecamaras.org.ve/feed/",
		kind: "rss",
		region: "national",
		stance: "trade-body",
		homepage: "https://www.fedecamaras.org.ve/",
		intervalMs: 180 * MIN,
	},
	{
		id: "labpaz",
		name: "Laboratorio de Paz",
		url: "https://labpaz.org/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://labpaz.org/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "ovcs",
		name: "Observatorio Venezolano de Conflictividad Social",
		url: "https://www.observatoriodeconflictos.org.ve/feed/atom",
		kind: "atom",
		region: "national",
		stance: "ngo",
		homepage: "https://www.observatoriodeconflictos.org.ve/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "transparencia-venezuela",
		name: "Transparencia Venezuela",
		url: "https://transparenciave.org/feed/atom/",
		kind: "atom",
		region: "national",
		stance: "ngo",
		homepage: "https://transparenciave.org/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "utopix",
		name: "Utopix",
		url: "https://utopix.cc/feed/",
		kind: "rss",
		region: "national",
		stance: "ngo",
		homepage: "https://utopix.cc/",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "venamcham",
		name: "Venamcham",
		url: "https://www.venamcham.org/feed/",
		kind: "rss",
		region: "national",
		stance: "trade-body",
		homepage: "https://venamcham.org/",
		intervalMs: 180 * MIN,
	},
	// Regional outlets, by state.
	{
		id: "diario-el-tigrense",
		name: "Diario El Tigrense (Anzoátegui)",
		url: "https://www.diarioeltigrense.com/feed/",
		kind: "rss",
		region: "VE-B",
		stance: "commercial",
		homepage: "https://www.diarioeltigrense.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "diario-el-vistazo",
		name: "Diario El Vistazo (Anzoátegui)",
		url: "https://diarioelvistazo.com/feed/",
		kind: "rss",
		region: "VE-B",
		stance: "commercial",
		homepage: "https://diarioelvistazo.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "noticias-de-aqui",
		name: "Noticias de Aquí (Anzoátegui)",
		url: "https://noticiasdeaqui.co/feed/",
		kind: "rss",
		region: "VE-B",
		stance: "commercial",
		homepage: "https://noticiasdeaqui.co/",
		intervalMs: 20 * MIN,
	},
	{
		id: "notiapure",
		name: "Notiapure (Apure)",
		url: "https://notiapure.com.ve/feed/",
		kind: "rss",
		region: "VE-C",
		stance: "commercial",
		homepage: "https://notiapure.com.ve/",
		intervalMs: 10 * MIN,
	},
	{
		id: "ciudad-maracay",
		name: "Ciudad MCY (Aragua)",
		url: "https://ciudadmcy.info.ve/feed",
		kind: "rss",
		region: "VE-D",
		stance: "state",
		homepage: "https://ciudadmcy.info.ve/",
		intervalMs: 10 * MIN,
	},
	{
		id: "notimax-plus",
		name: "Notimax Plus (Barinas)",
		url: "https://www.notimaxplus.com/feeds/posts/default",
		kind: "atom",
		region: "VE-E",
		stance: "commercial",
		homepage: "https://www.notimaxplus.com/",
		intervalMs: 180 * MIN,
	},
	{
		id: "el-guayanes",
		name: "Diario El Guayanés (Bolívar)",
		url: "https://prensaelguayanes.com.ve/feed/",
		kind: "rss",
		region: "VE-F",
		stance: "commercial",
		homepage: "https://prensaelguayanes.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "infosur-guayana",
		name: "InfoSur Guayana (Bolívar)",
		url: "https://infosurguayana.com.ve/feed/",
		kind: "rss",
		region: "VE-F",
		stance: "commercial",
		homepage: "https://infosurguayana.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "acn",
		name: "Agencia Carabobeña de Noticias (Carabobo)",
		url: "https://acn.com.ve/feed/",
		kind: "rss",
		region: "VE-G",
		stance: "commercial",
		homepage: "https://www.acn.com.ve/",
		intervalMs: 20 * MIN,
	},
	{
		id: "el-carabobeno",
		name: "El Carabobeño (Carabobo)",
		url: "https://www.el-carabobeno.com/feed/",
		kind: "rss",
		region: "VE-G",
		stance: "independent",
		homepage: "https://www.el-carabobeno.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "noticias24-carabobo",
		name: "Noticias 24 Carabobo",
		url: "https://noticias24carabobo.com/feed/",
		kind: "rss",
		region: "VE-G",
		stance: "commercial",
		homepage: "https://noticias24carabobo.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "noticiero-de-venezuela",
		name: "Noticiero de Venezuela (Carabobo)",
		url: "https://noticierodevenezuela.com/feed/",
		kind: "rss",
		region: "VE-G",
		stance: "commercial",
		homepage: "https://noticierodevenezuela.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "cactus24",
		name: "Cactus24 (Falcón)",
		url: "https://cactus24.com.ve/feed/",
		kind: "rss",
		region: "VE-I",
		stance: "commercial",
		homepage: "https://cactus24.com.ve/",
		intervalMs: 10 * MIN,
	},
	{
		id: "falcon-informativa",
		name: "Falcón Informativa",
		url: "https://falconinformativa.com/feed/",
		kind: "rss",
		region: "VE-I",
		stance: "commercial",
		homepage: "https://falconinformativa.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "el-tubazo",
		name: "El Tubazo Digital (Guárico)",
		url: "https://eltubazodigital.com/feed/",
		kind: "rss",
		region: "VE-J",
		stance: "commercial",
		homepage: "https://eltubazodigital.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "cabudare-digital",
		name: "Cabudare Digital (Lara)",
		url: "https://www.cabudaredigital.com/web/feed/",
		kind: "rss",
		region: "VE-K",
		stance: "commercial",
		homepage: "https://www.cabudaredigital.com/",
		intervalMs: 180 * MIN,
	},
	{
		id: "ciudad-bqto",
		name: "Ciudad BQTO (Lara)",
		url: "https://ciudadbqto.com/feed/",
		kind: "rss",
		region: "VE-K",
		stance: "state",
		homepage: "https://www.ciudadbqto.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "naguara",
		name: "NaGuara (Lara)",
		url: "https://naguara.com/feed/",
		kind: "rss",
		region: "VE-K",
		stance: "commercial",
		homepage: "https://naguara.com/",
		intervalMs: 180 * MIN,
	},
	{
		id: "comunicacion-continua",
		name: "Comunicación Continua (Mérida)",
		url: "https://comunicacioncontinua.com/feed/",
		kind: "rss",
		region: "VE-L",
		stance: "independent",
		homepage: "https://comunicacioncontinua.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "reporteros-de-merida",
		name: "Reporteros de Mérida",
		url: "https://www.reporterosdemerida.com.ve/feeds/posts/default",
		kind: "atom",
		region: "VE-L",
		stance: "commercial",
		homepage: "https://www.reporterosdemerida.com.ve/",
		intervalMs: 60 * MIN,
	},
	{
		id: "la-revista-del-tuy",
		name: "La Revista del Tuy (Miranda)",
		url: "https://larevistadeltuy.com/feed/",
		kind: "rss",
		region: "VE-M",
		stance: "commercial",
		homepage: "https://larevistadeltuy.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "la-voz-del-tuy",
		name: "La Voz del Tuy (Miranda)",
		url: "https://lavozdeltuy.com/feed/",
		kind: "rss",
		region: "VE-M",
		stance: "commercial",
		homepage: "https://lavozdeltuy.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "tuy-informa",
		name: "TuyInforma (Miranda)",
		url: "https://www.tuyinforma.com/feed/",
		kind: "rss",
		region: "VE-M",
		stance: "commercial",
		homepage: "https://www.tuyinforma.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "la-prensa-de-monagas",
		name: "La Prensa de Monagas",
		url: "https://laprensademonagas.com/feed/",
		kind: "rss",
		region: "VE-N",
		stance: "commercial",
		homepage: "https://www.laprensademonagas.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "notiespartano",
		name: "Notiespartano (Nueva Esparta)",
		url: "https://notiespartano.com/feed/",
		kind: "rss",
		region: "VE-O",
		stance: "commercial",
		homepage: "https://www.notiespartano.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "crn-portuguesa",
		name: "Circuito Regional de Noticias (Portuguesa)",
		url: "https://crn.com.ve/feed/",
		kind: "rss",
		region: "VE-P",
		stance: "commercial",
		homepage: "https://crn.com.ve/",
		intervalMs: 60 * MIN,
	},
	{
		id: "portuguesa-al-dia",
		name: "Portuguesa al Día",
		url: "https://portuguesaaldia.com/feed/",
		kind: "rss",
		region: "VE-P",
		stance: "commercial",
		homepage: "https://portuguesaaldia.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "portuguesa-reporta",
		name: "Portuguesa Reporta",
		url: "https://portuguesareporta.com/feed/",
		kind: "rss",
		region: "VE-P",
		stance: "commercial",
		homepage: "https://portuguesareporta.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "carupanero",
		name: "Carupanero.com (Sucre)",
		url: "https://carupanero.com/feed/",
		kind: "rss",
		region: "VE-R",
		stance: "commercial",
		homepage: "https://carupanero.com/",
		intervalMs: 180 * MIN,
	},
	{
		id: "tachira-news",
		name: "Táchira News",
		url: "https://www.tachiranews.com/feed/",
		kind: "rss",
		region: "VE-S",
		stance: "commercial",
		homepage: "https://www.tachiranews.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "yaracuy-al-dia",
		name: "Yaracuy al Día",
		url: "https://yaracuyaldia.com/feed/",
		kind: "rss",
		region: "VE-U",
		stance: "commercial",
		homepage: "https://yaracuyaldia.com/",
		intervalMs: 20 * MIN,
	},
	{
		id: "asi-es-noticias",
		name: "Así Es Noticias (Zulia)",
		url: "https://asiesnoticias.com/feed/",
		kind: "rss",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://asiesnoticias.com/",
		intervalMs: 60 * MIN,
	},
	{
		id: "digital-58",
		name: "Digital 58 (Zulia)",
		url: "https://digital58.com.ve/site/feed/",
		kind: "rss",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://digital58.com.ve/",
		intervalMs: 60 * MIN,
	},
	{
		id: "noticia-al-minuto",
		name: "Noticia al Minuto (Zulia)",
		url: "https://noticiaalminuto.com/feed/",
		kind: "rss",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://noticiaalminuto.com/",
		intervalMs: 10 * MIN,
	},
	{
		id: "notizulia",
		name: "Notizulia (Zulia)",
		url: "https://notizulia.net/feed/",
		kind: "rss",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://notizulia.net/",
		intervalMs: 60 * MIN,
	},
	{
		id: "primera-edicion-col",
		name: "Primera Edición COL (Zulia)",
		url: "https://primeraedicioncol.com/feed/",
		kind: "rss",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://primeraedicioncol.com/",
		intervalMs: 20 * MIN,
	},
	// Diaspora.
	{
		id: "al-navio",
		name: "Al Navío",
		url: "https://alnavio.es/feed/",
		kind: "rss",
		region: "diaspora",
		stance: "commercial",
		homepage: "https://alnavio.es/",
		lang: "es",
		intervalMs: 10 * MIN,
	},
	{
		id: "el-venezolano-hou",
		name: "El Venezolano Houston",
		url: "https://www.elvenezolanohouston.com/feed/",
		kind: "rss",
		region: "diaspora",
		stance: "commercial",
		homepage: "https://elvenezolanohouston.com/",
		country: "US",
		lang: "es",
		intervalMs: 60 * MIN,
	},
	// International desks in Spanish (a Venezuela feed, or only items that mention Venezuela).
	{
		id: "14ymedio",
		name: "14ymedio",
		url: "https://www.14ymedio.com/rss/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.14ymedio.com/",
		lang: "es",
		country: "CU",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "20minutos-internacional",
		name: "20minutos (Internacional)",
		url: "https://www.20minutos.es/rss/internacional/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.20minutos.es/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "abc-color-py",
		name: "ABC Color (Paraguay, Internacionales)",
		url: "https://www.abc.com.py/arc/outboundfeeds/rss/category/internacionales/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.abc.com.py/",
		lang: "es",
		country: "PY",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "amnesty-es-venezuela",
		name: "Amnistía Internacional (Venezuela)",
		url: "https://www.amnesty.org/es/location/americas/south-america/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "ngo",
		homepage: "https://www.amnesty.org/es/location/americas/south-america/venezuela/",
		lang: "es",
		country: "GB",
		genre: "rights",
		publisher: "amnesty-en-venezuela",
		intervalMs: 180 * MIN,
	},
	{
		id: "anadolu-es",
		name: "Anadolu Agency (Español)",
		url: "https://www.aa.com.tr/es/rss/default?cat=mundo",
		kind: "rss",
		region: "international",
		stance: "state-funded",
		homepage: "https://www.aa.com.tr/es",
		lang: "es",
		country: "TR",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "andina",
		name: "Andina (Agencia Peruana de Noticias)",
		url: "https://andina.pe/agencia/rss/4.xml",
		kind: "rss",
		region: "international",
		stance: "state-funded",
		homepage: "https://andina.pe/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "bloomberg-linea",
		name: "Bloomberg Línea",
		url: "https://www.bloomberglinea.com/arc/outboundfeeds/rss/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.bloomberglinea.com/",
		lang: "es",
		country: "US",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "caracol-radio",
		name: "Caracol Radio",
		url: "https://caracol.com.co/arc/outboundfeeds/rss/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://caracol.com.co/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "cibercuba",
		name: "CiberCuba",
		url: "https://www.cibercuba.com/rss.xml",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.cibercuba.com/",
		lang: "es",
		country: "CU",
		onlyVenezuela: true,
		intervalMs: 30 * MIN,
	},
	{
		id: "diario-de-cuba",
		name: "Diario de Cuba",
		url: "https://diariodecuba.com/rss.xml",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://diariodecuba.com/",
		lang: "es",
		country: "CU",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "diario-libre-mundo",
		name: "Diario Libre (Mundo)",
		url: "https://www.diariolibre.com/rss/mundo.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.diariolibre.com/",
		lang: "es",
		country: "DO",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "el-colombiano-internacional",
		name: "El Colombiano (Internacional)",
		url: "https://www.elcolombiano.com/rss/Internacional.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.elcolombiano.com/",
		lang: "es",
		country: "CO",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "el-comercio-pe-mundo",
		name: "El Comercio (Perú, Mundo)",
		url: "https://elcomercio.pe/arc/outboundfeeds/rss/category/mundo/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://elcomercio.pe/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "el-confidencial-mundo",
		name: "El Confidencial (Mundo)",
		url: "https://rss.elconfidencial.com/mundo/",
		kind: "atom",
		region: "international",
		stance: "commercial",
		homepage: "https://www.elconfidencial.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "el-correo-internacional",
		name: "El Correo (Internacional)",
		url: "https://www.elcorreo.com/rss/2.0/?section=internacional",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.elcorreo.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "el-debate-internacional",
		name: "El Debate (Internacional)",
		url: "https://www.eldebate.com/rss/internacional.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.eldebate.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "el-espanol-mundo",
		name: "El Español (Mundo)",
		url: "https://www.elespanol.com/rss/mundo/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.elespanol.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "el-heraldo-co",
		name: "El Heraldo (Barranquilla)",
		url: "https://www.elheraldo.co/arc/outboundfeeds/rss/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.elheraldo.co/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "el-salto-venezuela",
		name: "El Salto (Venezuela)",
		url: "https://www.elsaltodiario.com/venezuela/feed",
		kind: "atom",
		region: "international",
		stance: "independent",
		homepage: "https://www.elsaltodiario.com/venezuela",
		lang: "es",
		country: "ES",
		intervalMs: 180 * MIN,
	},
	{
		id: "el-tiempo-co-venezuela",
		name: "El Tiempo (Venezuela)",
		url: "https://www.eltiempo.com/rss/mundo_venezuela.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.eltiempo.com/mundo/venezuela",
		lang: "es",
		country: "CO",
		publisher: "el-tiempo-co",
		intervalMs: 60 * MIN,
	},
	{
		id: "el-universal-co",
		name: "El Universal (Cartagena)",
		url: "https://www.eluniversal.com.co/arc/outboundfeeds/rss/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.eluniversal.com.co/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "eldiario-es-internacional",
		name: "elDiario.es (Internacional)",
		url: "https://www.eldiario.es/rss/internacional/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.eldiario.es/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "europa-press-internacional",
		name: "Europa Press (Internacional)",
		url: "https://www.europapress.es/rss/rss.aspx?ch=00069",
		kind: "rss",
		region: "international",
		stance: "agency",
		homepage: "https://www.europapress.es/internacional/",
		lang: "es",
		publisher: "europa-press-latam",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "expansion-es",
		name: "Expansión (Economía)",
		url: "https://e00-expansion.uecdn.es/rss/economia.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.expansion.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "infolibre",
		name: "infoLibre",
		url: "https://www.infolibre.es/rss",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.infolibre.es/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "insight-crime-es",
		name: "InSight Crime (Español)",
		url: "https://insightcrime.org/es/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://es.insightcrime.org/",
		lang: "es",
		country: "CO",
		publisher: "insight-crime-venezuela",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "ips-noticias",
		name: "IPS Noticias",
		url: "https://ipsnoticias.net/feed/",
		kind: "rss",
		region: "international",
		stance: "agency",
		homepage: "https://ipsnoticias.net/",
		lang: "es",
		country: "IT",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "la-diaria-uy",
		name: "la diaria (Uruguay)",
		url: "https://ladiaria.com.uy/feeds/articulos/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://ladiaria.com.uy/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "la-nacion-ar-mundo",
		name: "La Nación (Argentina, El Mundo)",
		url: "https://www.lanacion.com.ar/arc/outboundfeeds/rss/category/el-mundo/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.lanacion.com.ar/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "la-nacion-cr-mundo",
		name: "La Nación (Costa Rica, El Mundo)",
		url: "https://www.nacion.com/arc/outboundfeeds/rss/category/el-mundo/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.nacion.com/",
		lang: "es",
		country: "CR",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "la-prensa-hn",
		name: "La Prensa (Honduras, Mundo)",
		url: "https://www.laprensa.hn/rss/mundo",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.laprensa.hn/",
		lang: "es",
		country: "HN",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "la-prensa-pa-mundo",
		name: "La Prensa (Panamá, Mundo)",
		url: "https://www.prensa.com/arc/outboundfeeds/rss/category/mundo/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.prensa.com/",
		lang: "es",
		country: "PA",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "la-republica-pe-mundo",
		name: "La República (Perú, Mundo)",
		url: "https://larepublica.pe/rss/mundo.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://larepublica.pe/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "la-silla-vacia-venezuela",
		name: "La Silla Vacía (tag Venezuela)",
		url: "https://www.lasillavacia.com/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.lasillavacia.com/",
		lang: "es",
		country: "CO",
		intervalMs: 180 * MIN,
	},
	{
		id: "la-tercera-mundo",
		name: "La Tercera (Mundo)",
		url: "https://www.latercera.com/arc/outboundfeeds/rss/category/mundo/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.latercera.com/",
		lang: "es",
		country: "CL",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "la-vanguardia-internacional",
		name: "La Vanguardia (Internacional)",
		url: "https://www.lavanguardia.com/rss/internacional.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.lavanguardia.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "las2orillas",
		name: "Las2orillas",
		url: "https://www.las2orillas.co/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.las2orillas.co/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "libertad-digital-internacional",
		name: "Libertad Digital (Internacional)",
		url: "https://feeds2.feedburner.com/libertaddigital/internacional",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.libertaddigital.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "mala-espina",
		name: "Mala Espina Check",
		url: "https://www.malaespinacheck.cl/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.malaespinacheck.cl/",
		lang: "es",
		genre: "fact-check",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "mercopress-es",
		name: "MercoPress (Español)",
		url: "https://es.mercopress.com/rss/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://es.mercopress.com/",
		lang: "es",
		country: "UY",
		publisher: "mercopress-en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "nodal-venezuela",
		name: "NODAL (tag Venezuela)",
		url: "https://www.nodal.am/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.nodal.am/",
		lang: "es",
		country: "AR",
		intervalMs: 180 * MIN,
	},
	{
		id: "okdiario-internacional",
		name: "OKdiario (Internacional)",
		url: "https://okdiario.com/internacional/feed",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://okdiario.com/",
		lang: "es",
		country: "ES",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "perfil-internacional",
		name: "Perfil (Internacional)",
		url: "https://www.perfil.com/feed/internacional",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.perfil.com/",
		lang: "es",
		country: "AR",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "prensa-latina",
		name: "Prensa Latina",
		url: "https://www.prensa-latina.cu/feed/",
		kind: "rss",
		region: "international",
		stance: "state-funded",
		homepage: "https://www.prensa-latina.cu/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 30 * MIN,
	},
	{
		id: "cooperativa-mundo",
		name: "Radio Cooperativa (Mundo)",
		url: "https://www.cooperativa.cl/noticias/site/tax/port/all/rss_3___1.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.cooperativa.cl/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "rpp",
		name: "RPP Noticias",
		url: "https://rpp.pe/rss",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://rpp.pe/",
		lang: "es",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "rt-actualidad",
		name: "RT en Español",
		url: "https://actualidad.rt.com/feeds/all.rss",
		kind: "rss",
		region: "international",
		stance: "state-funded",
		homepage: "https://actualidad.rt.com/",
		lang: "es",
		country: "RU",
		onlyVenezuela: true,
		intervalMs: 30 * MIN,
	},
	{
		id: "sputnik-mundo",
		name: "Sputnik Mundo",
		url: "https://noticiaslatam.lat/export/rss2/archive/index.xml",
		kind: "rss",
		region: "international",
		stance: "state-funded",
		homepage: "https://noticiaslatam.lat/",
		lang: "es",
		country: "RU",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "vanguardia-co",
		name: "Vanguardia (Bucaramanga)",
		url: "https://www.vanguardia.com/arc/outboundfeeds/rss/?outputType=xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.vanguardia.com/",
		lang: "es",
		country: "CO",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "verificado-mx",
		name: "Verificado (México)",
		url: "https://verificado.com.mx/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://verificado.com.mx/",
		lang: "es",
		genre: "fact-check",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	// International desks in English.
	{
		id: "amnesty-en-venezuela",
		name: "Amnesty International (Venezuela)",
		url: "https://www.amnesty.org/en/location/americas/south-america/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "ngo",
		homepage: "https://www.amnesty.org/en/location/americas/south-america/venezuela/",
		country: "GB",
		lang: "en",
		genre: "rights",
		intervalMs: 180 * MIN,
	},
	{
		id: "atlantic-council",
		name: "Atlantic Council",
		url: "https://www.atlanticcouncil.org/feed/",
		kind: "rss",
		region: "international",
		stance: "ngo",
		homepage: "https://www.atlanticcouncil.org/",
		country: "US",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "bbc-latin-america",
		name: "BBC News (Latin America)",
		url: "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.bbc.com/news/world/latin_america",
		country: "GB",
		lang: "en",
		publisher: "bbc-mundo",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "cnc3",
		name: "CNC3",
		url: "https://www.cnc3.co.tt/feed/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.cnc3.co.tt/",
		country: "TT",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "ft-venezuela",
		name: "Financial Times (Venezuela)",
		url: "https://www.ft.com/venezuela?format=rss",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.ft.com/venezuela",
		country: "GB",
		lang: "en",
		intervalMs: 180 * MIN,
	},
	{
		id: "france24-en-venezuela",
		name: "France 24 (Venezuela, English)",
		url: "https://www.france24.com/en/tag/venezuela/rss",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.france24.com/en/tag/venezuela/",
		country: "FR",
		lang: "en",
		publisher: "france24-es",
		intervalMs: 180 * MIN,
	},
	{
		id: "gcaptain",
		name: "gCaptain",
		url: "https://gcaptain.com/feed/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://gcaptain.com/",
		country: "US",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "global-voices-venezuela",
		name: "Global Voices (Venezuela)",
		url: "https://globalvoices.org/-/world/latin-america/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://globalvoices.org/-/world/latin-america/venezuela/",
		country: "NL",
		lang: "en",
		intervalMs: 180 * MIN,
	},
	{
		id: "govuk-venezuela-news",
		name: "GOV.UK (Venezuela news)",
		url: "https://www.gov.uk/search/news-and-communications.atom?world_locations%5B%5D=venezuela",
		kind: "atom",
		region: "international",
		stance: "state",
		homepage: "https://www.gov.uk/world/venezuela",
		country: "GB",
		lang: "en",
		genre: "official",
		intervalMs: 180 * MIN,
	},
	{
		id: "havana-times",
		name: "Havana Times",
		url: "https://havanatimes.org/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://havanatimes.org/",
		country: "CU",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "inews-guyana",
		name: "iNews Guyana",
		url: "https://inewsguyana.com/feed/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.inewsguyana.com/",
		country: "GY",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "insight-crime-venezuela",
		name: "InSight Crime (tag Venezuela)",
		url: "https://insightcrime.org/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://insightcrime.org/",
		country: "CO",
		lang: "en",
		intervalMs: 180 * MIN,
	},
	{
		id: "latin-america-reports-venezuela",
		name: "Latin America Reports (tag Venezuela)",
		url: "https://latinamericareports.com/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://latinamericareports.com/",
		country: "GB",
		lang: "en",
		intervalMs: 180 * MIN,
	},
	{
		id: "la-times-world",
		name: "Los Angeles Times (World & Nation)",
		url: "https://www.latimes.com/world-nation/rss2.0.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.latimes.com/world-nation",
		country: "US",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "mercopress-en",
		name: "MercoPress",
		url: "https://en.mercopress.com/rss/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://en.mercopress.com/",
		country: "UY",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "npr-world",
		name: "NPR (World)",
		url: "https://feeds.npr.org/1004/rss.xml",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.npr.org/sections/world/",
		country: "US",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "occrp",
		name: "OCCRP",
		url: "https://www.occrp.org/en/feed",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.occrp.org/",
		country: "NL",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "pbs-newshour-world",
		name: "PBS NewsHour (World)",
		url: "https://www.pbs.org/newshour/feeds/rss/world",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.pbs.org/newshour/",
		country: "US",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "semafor",
		name: "Semafor",
		url: "https://www.semafor.com/rss.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.semafor.com/",
		country: "US",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "economist-americas",
		name: "The Economist (The Americas)",
		url: "https://www.economist.com/the-americas/rss.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.economist.com/the-americas",
		country: "GB",
		lang: "en",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "guardian-americas",
		name: "The Guardian (Americas)",
		url: "https://www.theguardian.com/world/americas/rss",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.theguardian.com/world/americas",
		country: "GB",
		lang: "en",
		publisher: "guardian-ve",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	// International desks in Portuguese (Brazil, the Roraima border, Portugal).
	{
		id: "agencia-brasil-internacional",
		name: "Agência Brasil (Internacional)",
		url: "https://agenciabrasil.ebc.com.br/rss/internacional/feed.xml",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://agenciabrasil.ebc.com.br/internacional",
		lang: "pt",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "bbc-brasil",
		name: "BBC News Brasil",
		url: "https://feeds.bbci.co.uk/portuguese/rss.xml",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.bbc.com/portuguese",
		country: "GB",
		lang: "pt",
		publisher: "bbc-mundo",
		onlyVenezuela: true,
		intervalMs: 180 * MIN,
	},
	{
		id: "brasil-de-fato-venezuela",
		name: "Brasil de Fato (tag Venezuela)",
		url: "https://www.brasildefato.com.br/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.brasildefato.com.br/",
		lang: "pt",
		intervalMs: 180 * MIN,
	},
	{
		id: "carta-capital-venezuela",
		name: "CartaCapital (tag Venezuela)",
		url: "https://www.cartacapital.com.br/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.cartacapital.com.br/",
		lang: "pt",
		intervalMs: 180 * MIN,
	},
	{
		id: "folha-bv-venezuela",
		name: "Folha de Boa Vista (tag Venezuela)",
		url: "https://www.folhabv.com.br/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://folhabv.com.br/",
		lang: "pt",
		intervalMs: 180 * MIN,
	},
	{
		id: "folha-mundo",
		name: "Folha de S.Paulo (Mundo)",
		url: "https://feeds.folha.uol.com.br/mundo/rss091.xml",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www1.folha.uol.com.br/mundo/",
		lang: "pt",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "g1-mundo",
		name: "g1 (Mundo)",
		url: "https://g1.globo.com/rss/g1/mundo/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://g1.globo.com/mundo/",
		country: "BR",
		lang: "pt",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "metropoles-venezuela",
		name: "Metrópoles (tag Venezuela)",
		url: "https://www.metropoles.com/tag/venezuela/feed",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://www.metropoles.com/",
		country: "BR",
		lang: "pt",
		intervalMs: 180 * MIN,
	},
	{
		id: "observador-mundo",
		name: "Observador (Mundo)",
		url: "https://observador.pt/seccao/mundo/feed/",
		kind: "rss",
		region: "international",
		stance: "commercial",
		homepage: "https://observador.pt/seccao/mundo/",
		country: "PT",
		lang: "pt",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "opera-mundi-venezuela",
		name: "Opera Mundi (tag Venezuela)",
		url: "https://operamundi.uol.com.br/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://operamundi.uol.com.br/",
		lang: "pt",
		intervalMs: 180 * MIN,
	},
	{
		id: "poder360-venezuela",
		name: "Poder360 (tag Venezuela)",
		url: "https://www.poder360.com.br/tag/venezuela/feed/",
		kind: "rss",
		region: "international",
		stance: "independent",
		homepage: "https://www.poder360.com.br/",
		lang: "pt",
		intervalMs: 180 * MIN,
	},
	{
		id: "rtp-mundo",
		name: "RTP Notícias (Mundo)",
		url: "https://www.rtp.pt/noticias/rss/mundo",
		kind: "rss",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.rtp.pt/noticias/mundo",
		country: "PT",
		lang: "pt",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	{
		id: "sputnik-brasil",
		name: "Sputnik Brasil",
		url: "https://noticiabrasil.net.br/export/rss2/archive/index.xml",
		kind: "rss",
		region: "international",
		stance: "state-funded",
		homepage: "https://noticiabrasil.net.br/",
		country: "RU",
		lang: "pt",
		publisher: "sputnik-mundo",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
	},
	// YouTube channels (opt-in: youtube.com's robots.txt excludes /feeds/videos.xml).
	{
		id: "yt-bbc-mundo",
		name: "BBC News Mundo (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCUBIrDsIVzRpKsClMlSlTpQ",
		kind: "youtube",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.youtube.com/channel/UCUBIrDsIVzRpKsClMlSlTpQ",
		lang: "es",
		country: "GB",
		publisher: "bbc-mundo",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-dw-es",
		name: "DW Español (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCT4Jg8h03dD0iN3Pb5L0PMA",
		kind: "youtube",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.youtube.com/channel/UCT4Jg8h03dD0iN3Pb5L0PMA",
		lang: "es",
		country: "DE",
		publisher: "dw-es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-euronews-es",
		name: "euronews Español (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCyoGb3SMlTlB8CLGVH4c8Rw",
		kind: "youtube",
		region: "international",
		stance: "public-broadcaster",
		homepage: "https://www.youtube.com/channel/UCyoGb3SMlTlB8CLGVH4c8Rw",
		lang: "es",
		country: "FR",
		publisher: "euronews-es",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-la-republica-pe",
		name: "La República Perú (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-B7Xv56uNRDkj0vC3QW8Cg",
		kind: "youtube",
		region: "international",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UC-B7Xv56uNRDkj0vC3QW8Cg",
		lang: "es",
		country: "PE",
		publisher: "la-republica-pe-mundo",
		onlyVenezuela: true,
		intervalMs: 30 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-nmas-univision",
		name: "N+ Univision (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC32TdiIsh_5X8tKr_9rKQyA",
		kind: "youtube",
		region: "international",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UC32TdiIsh_5X8tKr_9rKQyA",
		lang: "es",
		country: "US",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-telemundo",
		name: "Noticias Telemundo (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCRwA1NUcUnwsly35ikGhp0A",
		kind: "youtube",
		region: "international",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UCRwA1NUcUnwsly35ikGhp0A",
		lang: "es",
		country: "US",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-telesur-en",
		name: "teleSUR English (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCmuTmpLY35O3csvhyA6vrkg",
		kind: "youtube",
		region: "international",
		stance: "state",
		homepage: "https://www.youtube.com/channel/UCmuTmpLY35O3csvhyA6vrkg",
		country: "VE",
		lang: "en",
		publisher: "telesur",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-todo-noticias",
		name: "Todo Noticias (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCj6PcyLvpnIRT_2W_mwa9Aw",
		kind: "youtube",
		region: "international",
		stance: "commercial",
		homepage: "https://www.youtube.com/channel/UCj6PcyLvpnIRT_2W_mwa9Aw",
		lang: "es",
		country: "AR",
		onlyVenezuela: true,
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	// YouTube channels of Venezuelan outlets verified by the YouTube research pass (one feed fetch each with the
	// project User-Agent, newest video 2026-09-08..25); youtube.com's feed server then answered 404 to every re-probe.
	{
		id: "yt-ciudad-ccs",
		name: "Ciudad CCS (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCw572heLSpa-A1jBGFS80Aw",
		kind: "youtube",
		region: "VE-A",
		stance: "state",
		homepage: "https://ciudadccs.info/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-trt",
		name: "TRT Táchira (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCKOjoZ02plkTlGzu3D5kzyQ",
		kind: "youtube",
		region: "VE-S",
		stance: "commercial",
		homepage: "https://www.trt.gob.ve/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-noticia-al-dia",
		name: "Noticia al Día (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCDbIfWeATvuTK8CkDUmrT3g",
		kind: "youtube",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://noticialdia.com/",
		publisher: "noticia-al-dia",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-version-final",
		name: "Versión Final (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVZIChCdaVg0QPGzFD4sULg",
		kind: "youtube",
		region: "VE-V",
		stance: "commercial",
		homepage: "https://diarioversionfinal.com/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-evtv",
		name: "EVTV Miami (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCshe7-1A5MN_ArHsG_3V41g",
		kind: "youtube",
		region: "diaspora",
		stance: "commercial",
		homepage: "https://evtvmiami.com/",
		country: "US",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-ntn24ve",
		name: "NTN24 Venezuela (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFK38lePM6zqQ2CYfQyqdHA",
		kind: "youtube",
		region: "international",
		stance: "commercial",
		homepage: "https://www.ntn24.com/",
		country: "CO",
		publisher: "yt-ntn24",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-analitica",
		name: "Analítica TV (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMO9iMNuVm3AsByCAPXJ8Hw",
		kind: "youtube",
		region: "national",
		stance: "commercial",
		homepage: "https://www.analitica.com/",
		publisher: "analitica",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-antv",
		name: "ANTV Asamblea Nacional (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCpqNgxhtBcCk4mVIqz26W2w",
		kind: "youtube",
		region: "national",
		stance: "state",
		homepage: "https://www.canalantv.com.ve/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-armando-info",
		name: "Armando.info (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC0MsRPI1cevUHFFJZPAC5rQ",
		kind: "youtube",
		region: "national",
		stance: "independent",
		homepage: "https://armando.info/",
		publisher: "armando-info",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-el-nacional",
		name: "El Nacional (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UClCB13duZuVgCPXyG1Jq4Qw",
		kind: "youtube",
		region: "national",
		stance: "commercial",
		homepage: "https://www.elnacional.com/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-impacto-ve",
		name: "Impacto Venezuela (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCTK-HeQsG6v8Fs0iaMiETvw",
		kind: "youtube",
		region: "national",
		stance: "commercial",
		homepage: "https://impactove.com/",
		publisher: "impacto-ve",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-la-gran-aldea",
		name: "La Gran Aldea (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6TwmOyv43wa7aT1lz7r6Lg",
		kind: "youtube",
		region: "national",
		stance: "independent",
		homepage: "https://lagranaldea.com/",
		publisher: "la-gran-aldea",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-venevision-noticias",
		name: "Noticias Venevisión (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCR1tLg8fy9dklmhZPf0qCWQ",
		kind: "youtube",
		region: "national",
		stance: "commercial",
		homepage: "https://noticiasvenevision.com/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-radio-fe-y-alegria",
		name: "Radio Fe y Alegría Noticias (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCC4jcO4YNhsNkng6ptVulug",
		kind: "youtube",
		region: "national",
		stance: "independent",
		homepage: "https://www.radiofeyalegrianoticias.com/",
		publisher: "radio-fe-y-alegria",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-rnv-noticias",
		name: "RNV (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQjOwn6SIaKrrHr_Dm34DiQ",
		kind: "youtube",
		region: "national",
		stance: "state",
		homepage: "https://www.rnv.gob.ve/",
		publisher: "rnv",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-runrunes",
		name: "Runrunes (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC71_n5e7nvio2aEEVu7K_5g",
		kind: "youtube",
		region: "national",
		stance: "independent",
		homepage: "https://runrun.es/",
		publisher: "runrunes",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	{
		id: "yt-union-radio",
		name: "Unión Radio Noticias (YouTube)",
		url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCArtPwJFZpjO-5MM-pdN9AA",
		kind: "youtube",
		region: "national",
		stance: "commercial",
		homepage: "https://unionradio.net/",
		intervalMs: 60 * MIN,
		note: ROBOTS_NOTE,
	},
	// Public Telegram channels (src/adapters/telegram/channels.ts): each counts under its outlet when it has one.
	...TELEGRAM_CHANNELS,
];
