/**
 * Names-only place index for the command palette: every municipality (INE via OCHA COD-AB) and every city of
 * 30,000 people or more (GeoNames, CC BY 4.0), each with its state. No geometry, so it costs ~3 KB gzip instead
 * of the 50 KB the municipality outlines would.
 *
 * Usage: bun scripts/build-places.ts → web/src/lib/places.gen.ts
 * Format: "|"-separated records, each a kind letter (M municipality, C city), the 4-digit municipality P-code
 * without "VE" (its first two digits are the state), then the name. Example: "C2313Maracaibo".
 */
import { join } from "node:path";

interface Entry {
	kind: string;
	name: string;
	municipalityCode?: string;
	population?: number;
}

const MIN_CITY = 30_000;
const root = join(import.meta.dir, "..");
const gazetteer = (await Bun.file(join(root, "src", "geo", "data", "gazetteer.json")).json()) as {
	entries: Entry[];
};

const records: string[] = [];
const seen = new Set<string>();
for (const e of gazetteer.entries) {
	const code = e.municipalityCode?.slice(2);
	if (!code || !/^\d{4}$/.test(code) || e.name.includes("|")) continue;
	const kind =
		e.kind === "municipality" ? "M" : e.kind === "city" && (e.population ?? 0) >= MIN_CITY ? "C" : null;
	if (!kind) continue;
	const record = `${kind}${code}${e.name}`;
	// A city named like its own municipality (Maracaibo in Maracaibo) is one search result, not two.
	if (seen.has(record) || seen.has(`M${code}${e.name}`)) continue;
	seen.add(record);
	records.push(record);
}

const out = join(root, "web", "src", "lib", "places.gen.ts");
await Bun.write(
	out,
	`// Generated by scripts/build-places.ts from src/geo/data/gazetteer.json. Do not edit.
// Municipalities: INE Venezuela via OCHA COD-AB (CC BY-IGO 3.0). Cities of ${MIN_CITY.toLocaleString("en")}+: GeoNames (CC BY 4.0).
export const PLACES = ${JSON.stringify(records.join("|"))};
`,
);
console.log(`${out}: ${records.length} places`);
