import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ADAPTERS } from "../src/adapters/registry.ts";
import { dataSourcesMarkdown, generated, runtimePackages, withReadmeBlock } from "./gen-docs.ts";

const ROOT = join(import.meta.dir, "..");

test("generated files are current (run `bun scripts/gen-docs.ts` after adding a source or a dependency)", () => {
	for (const file of generated()) {
		expect({ path: file.path, content: readFileSync(join(ROOT, file.path), "utf8") }).toEqual({
			path: file.path,
			content: file.content,
		});
	}
});

test("the catalogue lists every adapter once, with its licence link", () => {
	const md = dataSourcesMarkdown();
	for (const a of ADAPTERS) {
		expect(md.split(`\`${a.id}\``).length - 1).toBe(1);
		expect(md).toContain(a.licence.url);
	}
});

test("every bundled runtime package declares a licence", () => {
	for (const p of runtimePackages()) expect(p.license).not.toBe("UNKNOWN");
});

test("the README block is replaced between its markers only", () => {
	const readme =
		"a\n<!-- sources:start (generated by bun scripts/gen-docs.ts) -->\nold\n<!-- sources:end -->\nb\n";
	expect(withReadmeBlock(readme, "new")).toBe(
		"a\n<!-- sources:start (generated by bun scripts/gen-docs.ts) -->\nnew\n<!-- sources:end -->\nb\n",
	);
	expect(() => withReadmeBlock("no markers", "x")).toThrow();
});
