/**
 * Generates the files that must follow the code: the data-source catalogue (docs/DATA-SOURCES.md), the sources
 * summary inside README.md, and NOTICE (third-party libraries and data licences). They are derived from the
 * adapter registry and the installed runtime dependencies, so they stay current as sources are added.
 *
 *   bun scripts/gen-docs.ts          rewrite the files
 *   bun scripts/gen-docs.ts --check  exit 1 if any file is out of date (also enforced by gen-docs.test.ts)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import pkg from "../package.json" with { type: "json" };
import { ADAPTERS } from "../src/adapters/registry.ts";
import type { Adapter, Layer } from "../src/core/types.ts";

const ROOT = join(import.meta.dir, "..");

const LAYER_TITLE: Record<Layer, string> = {
	money: "Money and prices",
	oil: "Oil and energy",
	internet: "Internet and power",
	earth: "Earth and weather",
	society: "Society and attention",
	news: "News",
	social: "Social",
};
const LAYER_ORDER: readonly Layer[] = ["money", "oil", "internet", "earth", "society", "news", "social"];

const MIN = 60_000;
function every(ms: number): string {
	if (ms < MIN) return `${Math.round(ms / 1000)} s`;
	if (ms < 60 * MIN) return `${Math.round(ms / MIN)} min`;
	if (ms < 24 * 60 * MIN) return `${Math.round(ms / (60 * MIN))} h`;
	return `${Math.round(ms / (24 * 60 * MIN))} d`;
}

/** Markdown table cells cannot contain pipes or line breaks. */
const cell = (text: string) => text.replaceAll("|", "\\|").replaceAll(/\s+/g, " ").trim();

function byLayer(adapters: readonly Adapter[]): Map<Layer, Adapter[]> {
	const groups = new Map<Layer, Adapter[]>();
	for (const layer of LAYER_ORDER) groups.set(layer, []);
	for (const a of adapters) groups.get(a.layer)?.push(a);
	return groups;
}

/** Access column: what a user needs to switch the source on. */
function access(a: Adapter): string {
	const parts: string[] = [];
	parts.push(a.keys.length === 0 ? "none" : `key: ${a.keys.map((k) => `\`${k}\``).join(", ")}`);
	if (a.optIn) parts.push("opt-in");
	if (a.note && !a.optIn) parts.push("on, noted");
	return parts.join(", ");
}

export function dataSourcesMarkdown(adapters: readonly Adapter[] = ADAPTERS): string {
	const lines: string[] = [
		"# Data sources",
		"",
		"<!-- Generated by `bun scripts/gen-docs.ts` from the adapter registry. Do not edit by hand. -->",
		"",
		`Vigía reads ${adapters.length} sources. Each row is one adapter in \`src/adapters/\`; the running app lists the`,
		"same sources, with live health, at `/fuentes` and `/estado`.",
		"",
		"- **Access**: `none` works with no key; `key` needs a free key the user adds in the setup guide (`/guia`);",
		"  `opt-in` is off until the user turns it on (the guide explains why, e.g. terms that are unclear about automated",
		"  access); `on, noted` is on by default with a note on how Vigía reads it (e.g. a feed the host's robots.txt",
		"  excludes, read at a low rate by the project's decision), and the user can turn it off.",
		"- **Raw rows**: whether the source's own rows are served by the raw API endpoints. `withheld` means the source's",
		"  terms do not allow passing its data on, so only results Vigía derives from it are shown, with attribution.",
		"- Data belongs to its publishers under the licences below; Vigía's own licence does not cover it.",
		"",
	];
	for (const [layer, group] of byLayer(adapters)) {
		if (group.length === 0) continue;
		lines.push(`## ${LAYER_TITLE[layer]} (${group.length})`, "");
		lines.push("| Source | Publisher | Every | Access | Licence | Raw rows |", "|---|---|---|---|---|---|");
		for (const a of group) {
			lines.push(
				`| [${cell(a.name.en)}](${a.homepage}) \`${a.id}\` | ${cell(a.provider)} | ${every(a.intervalMs)} | ${access(a)} | [${cell(a.licence.name)}](${a.licence.url}) | ${a.licence.raw === false ? "withheld" : "served"} |`,
			);
		}
		lines.push("");
	}
	return `${lines.join("\n").trimEnd()}\n`;
}

export function readmeSourcesBlock(adapters: readonly Adapter[] = ADAPTERS): string {
	const noKey = adapters.filter((a) => a.keys.length === 0 && !a.optIn).length;
	const rows = [...byLayer(adapters)]
		.filter(([, group]) => group.length > 0)
		.map(([layer, group]) => {
			const providers = [...new Set(group.map((a) => a.provider))];
			const shown = providers.slice(0, 6).map(cell).join(", ");
			const more = providers.length > 6 ? `, and ${providers.length - 6} more` : "";
			return `| ${LAYER_TITLE[layer]} | ${group.length} | ${shown}${more} |`;
		});
	return [
		`Vigía reads **${adapters.length} sources**; **${noKey}** of them work with no key at all. The full catalogue,`,
		"with publisher, refresh interval, access and licence for each, is generated from the adapter registry into",
		"[docs/DATA-SOURCES.md](docs/DATA-SOURCES.md).",
		"",
		"| Layer | Sources | Publishers |",
		"|---|---|---|",
		...rows,
	].join("\n");
}

const START = "<!-- sources:start (generated by bun scripts/gen-docs.ts) -->";
const END = "<!-- sources:end -->";

export function withReadmeBlock(readme: string, block: string): string {
	const a = readme.indexOf(START);
	const b = readme.indexOf(END);
	if (a === -1 || b === -1 || b < a) throw new Error(`README.md needs the markers ${START} … ${END}`);
	return `${readme.slice(0, a + START.length)}\n${block}\n${readme.slice(b)}`;
}

interface PackageInfo {
	readonly name: string;
	readonly version: string;
	readonly license: string;
	readonly homepage: string;
}

/** Runtime dependencies and everything they pull in (what ships in the client bundle and the binaries). */
export function runtimePackages(root = ROOT): PackageInfo[] {
	const seen = new Map<string, PackageInfo>();
	const visit = (name: string) => {
		if (seen.has(name)) return;
		const file = join(root, "node_modules", name, "package.json");
		if (!existsSync(file)) throw new Error(`${name} is not installed; run bun install`);
		const p = JSON.parse(readFileSync(file, "utf8")) as {
			version: string;
			license?: string;
			homepage?: string;
			repository?: string | { url?: string };
			dependencies?: Record<string, string>;
		};
		const repo = typeof p.repository === "string" ? p.repository : p.repository?.url;
		seen.set(name, {
			name,
			version: p.version,
			license: p.license ?? "UNKNOWN",
			homepage:
				p.homepage ??
				repo?.replace(/^git\+/, "").replace(/\.git$/, "") ??
				`https://www.npmjs.com/package/${name}`,
		});
		for (const dep of Object.keys(p.dependencies ?? {})) visit(dep);
	};
	for (const dep of Object.keys(pkg.dependencies)) visit(dep);
	return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** Data and assets bundled in the repository itself (not fetched at run time). */
const BUNDLED_DATA: readonly { what: string; source: string; licence: string }[] = [
	{
		what: "State and municipality boundaries (src/geo/data, web/src/map)",
		source: "Instituto Nacional de Estadística (INE) Venezuela, via OCHA COD-AB on HDX",
		licence: "CC BY-IGO 3.0",
	},
	{
		what: "Neighbouring countries (map context)",
		source: "Natural Earth (https://www.naturalearthdata.com)",
		licence: "Public domain",
	},
	{
		what: "Place names and city locations (gazetteer, command palette)",
		source: "GeoNames (https://www.geonames.org)",
		licence: "CC BY 4.0",
	},
	{
		what: "Oil and gas facility outlines (src/adapters/firms-flares/facilities.json)",
		source: "© OpenStreetMap contributors (https://www.openstreetmap.org/copyright)",
		licence: "ODbL 1.0 (the facilities file is a derived database under the same licence)",
	},
	{
		what: "Flare site locations used to match facilities (same file)",
		source: "World Bank Global Flaring and Methane Reduction Partnership (GFMR)",
		licence: "CC BY 4.0",
	},
	{
		what: "Fonts Archivo and Chivo Mono (web/static/fonts)",
		source: "The Archivo and Chivo Mono Project Authors (Omnibus-Type)",
		licence: "SIL Open Font License 1.1 (web/static/fonts/OFL.txt)",
	},
];

export function noticeText(adapters: readonly Adapter[] = ADAPTERS, root = ROOT): string {
	const out: string[] = [
		"Vigía",
		"Copyright 2026 elberacasa",
		"",
		"Vigía is licensed under the PolyForm Noncommercial License 1.0.0 (see LICENSE). That licence covers Vigía's",
		"own code only. The third-party software, data and fonts listed below keep their own licences.",
		"",
		"This file is generated by `bun scripts/gen-docs.ts`.",
		"",
		"================================================================================",
		"Third-party software bundled in the client and the release binaries",
		"================================================================================",
		"",
	];
	for (const p of runtimePackages(root)) out.push(`${p.name} ${p.version} (${p.license}) ${p.homepage}`);
	out.push(
		"",
		"Development tools (not distributed): see package.json devDependencies.",
		"",
		"================================================================================",
		"Data and assets included in this repository",
		"================================================================================",
		"",
	);
	for (const d of BUNDLED_DATA) out.push(`${d.what}`, `  Source: ${d.source}`, `  Licence: ${d.licence}`, "");
	out.push(
		"================================================================================",
		"Data fetched at run time",
		"================================================================================",
		"",
		"Vigía fetches data from the sources below when it runs. That data belongs to its publishers and is shown",
		"with their attribution. Where a licence is non-commercial (e.g. CC BY-NC-SA) or reserves redistribution, the",
		"same limits apply to anyone who runs or redistributes Vigía. Per-source details: docs/DATA-SOURCES.md.",
		"",
	);
	const licences = new Map<string, { name: string; url: string; attribution: string; sources: string[] }>();
	for (const a of adapters) {
		const entry = licences.get(a.licence.id) ?? {
			name: a.licence.name,
			url: a.licence.url,
			attribution: a.licence.attribution,
			sources: [],
		};
		entry.sources.push(a.id);
		licences.set(a.licence.id, entry);
	}
	for (const l of [...licences.values()].sort((a, b) => a.name.localeCompare(b.name))) {
		const sources = l.sources.length > 8 ? `${l.sources.length} sources` : l.sources.join(", ");
		out.push(`${l.name}`, `  ${l.url}`, `  Attribution: ${l.attribution}`, `  Used by: ${sources}`, "");
	}
	out.push(
		"Recorded test fixtures under src/adapters/*/fixtures are real responses from those sources, included only",
		"where the source's licence allows redistribution, under that same licence.",
	);
	return `${out.join("\n").trimEnd()}\n`;
}

export interface GeneratedFile {
	readonly path: string;
	readonly content: string;
}

export function generated(root = ROOT): GeneratedFile[] {
	const readme = readFileSync(join(root, "README.md"), "utf8");
	return [
		{ path: "docs/DATA-SOURCES.md", content: dataSourcesMarkdown() },
		{ path: "README.md", content: withReadmeBlock(readme, readmeSourcesBlock()) },
		{ path: "NOTICE", content: noticeText(ADAPTERS, root) },
	];
}

if (import.meta.main) {
	const check = process.argv.includes("--check");
	let stale = 0;
	for (const file of generated()) {
		const path = join(ROOT, file.path);
		const current = existsSync(path) ? readFileSync(path, "utf8") : "";
		if (current === file.content) continue;
		stale++;
		if (check) console.error(`${file.path} is out of date: run bun scripts/gen-docs.ts`);
		else {
			writeFileSync(path, file.content);
			console.log(`wrote ${file.path}`);
		}
	}
	if (check && stale > 0) process.exit(1);
	if (!check && stale === 0) console.log("generated files are current");
}
