import type { InstitutionKind } from "./types.ts";

/**
 * Public institutions a signal can be about. Hand-written and kept short on purpose: bodies of the Venezuelan
 * state that appear in the feeds Vigía reads. The organ names are the Gaceta Oficial index's own spelling, read
 * from the gaceta-oficial feed's stored issues on 2026-09-28 (every organ that published in the window is here);
 * the other bodies are the ones the outlet feeds and panels name (BCV, PDVSA, Corpoelec, CANTV…).
 *
 * `text` phrases link a headline to the institution: matched whole-word on the normalised text (src/news/text.ts),
 * so they must be names or acronyms that mean nothing else in Spanish headlines. Short generic acronyms ("AN",
 * "MP", "INE") are deliberately absent; the full name is used instead. Tested in registry.test.ts.
 */
export type InstitutionSpec = {
	readonly id: string;
	readonly kind: InstitutionKind;
	readonly es: string;
	readonly en: string;
	readonly short?: string;
	/** Other names people search by. */
	readonly aliases?: readonly string[];
	/** Phrases that link a headline to it (see above). */
	readonly text?: readonly string[];
	/** Gaceta Oficial organ names, word for word as the official index prints them. */
	readonly organs?: readonly string[];
	readonly homepage?: string;
	readonly attachedTo?: string;
	/** Vigía feeds that carry this institution's own figures. */
	readonly publishes?: readonly string[];
};

const MPP = "MINISTERIO DEL PODER POPULAR";

export const INSTITUTIONS: readonly InstitutionSpec[] = [
	// ——— the public powers ———
	{
		id: "inst.presidencia",
		kind: "presidency",
		es: "Presidencia de la República",
		en: "Office of the President",
		organs: ["PRESIDENCIA DE LA REPÚBLICA"],
		text: ["presidencia de la republica"],
	},
	{
		id: "inst.vicepresidencia",
		kind: "presidency",
		es: "Vicepresidencia de la República",
		en: "Office of the Vice President",
		organs: ["VICEPRESIDENCIA DE LA REPÚBLICA"],
		text: ["vicepresidencia de la republica"],
	},
	{
		id: "inst.vicepresidencia-comunicacion-cultura",
		kind: "presidency",
		es: "Vicepresidencia Sectorial de Comunicación y Cultura",
		en: "Sectoral Vice Presidency for Communication and Culture",
		organs: ["VICEPRESIDENCIA SECTORIAL DE COMUNICACIÓN Y CULTURA"],
	},
	{
		id: "inst.vicepresidencia-ciencia-educacion-salud",
		kind: "presidency",
		es: "Vicepresidencia Sectorial de Ciencia, Tecnología, Educación y Salud",
		en: "Sectoral Vice Presidency for Science, Technology, Education and Health",
		organs: ["VICEPRESIDENCIA SECTORIAL DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD"],
	},
	{
		id: "inst.an",
		kind: "branch",
		es: "Asamblea Nacional",
		en: "National Assembly",
		short: "AN",
		organs: ["ASAMBLEA NACIONAL"],
		text: ["asamblea nacional"],
		homepage: "https://www.asambleanacional.gob.ve/",
	},
	{
		id: "inst.tsj",
		kind: "branch",
		es: "Tribunal Supremo de Justicia",
		en: "Supreme Tribunal of Justice",
		short: "TSJ",
		organs: ["TRIBUNAL SUPREMO DE JUSTICIA"],
		text: ["tribunal supremo de justicia", "tsj"],
		homepage: "http://www.tsj.gob.ve/",
	},
	{
		id: "inst.cne",
		kind: "branch",
		es: "Consejo Nacional Electoral",
		en: "National Electoral Council",
		short: "CNE",
		organs: ["CONSEJO NACIONAL ELECTORAL"],
		text: ["consejo nacional electoral", "cne"],
		homepage: "http://www.cne.gob.ve/",
	},
	{
		id: "inst.ministerio-publico",
		kind: "branch",
		es: "Ministerio Público (Fiscalía General de la República)",
		en: "Public Prosecutor's Office",
		short: "Fiscalía",
		aliases: ["Fiscalía General de la República", "Fiscalía"],
		organs: ["MINISTERIO PÚBLICO"],
		text: ["ministerio publico", "fiscalia general de la republica"],
		homepage: "http://www.ministeriopublico.gob.ve/",
	},
	{
		id: "inst.contraloria",
		kind: "branch",
		es: "Contraloría General de la República",
		en: "Comptroller General",
		organs: ["CONTRALORÍA GENERAL DE LA REPÚBLICA"],
		text: ["contraloria general de la republica"],
	},
	{
		id: "inst.defensoria",
		kind: "branch",
		es: "Defensoría del Pueblo",
		en: "Ombudsman's Office",
		organs: ["DEFENSORÍA DEL PUEBLO"],
		text: ["defensoria del pueblo"],
	},
	{
		id: "inst.defensa-publica",
		kind: "branch",
		es: "Defensa Pública",
		en: "Public Defender's Office",
		organs: ["DEFENSA PÚBLICA"],
	},
	{
		id: "inst.consejo-moral-republicano",
		kind: "branch",
		es: "Consejo Moral Republicano (Poder Ciudadano)",
		en: "Republican Moral Council (Citizen Power)",
		organs: ["PODER CIUDADANO CONSEJO MORAL REPUBLICANO"],
		text: ["consejo moral republicano"],
	},
	{
		id: "inst.consejo-federal-de-gobierno",
		kind: "branch",
		es: "Consejo Federal de Gobierno",
		en: "Federal Government Council",
		organs: ["CONSEJO FEDERAL DE GOBIERNO"],
		text: ["consejo federal de gobierno"],
	},
	// ——— ministries (Gaceta Oficial organ names) ———
	{
		id: "inst.mpp-salud",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Salud",
		en: "Ministry of Health",
		short: "MPPS",
		organs: [`${MPP} PARA LA SALUD`],
		text: [
			"ministerio de salud",
			"ministerio para la salud",
			"ministerio del poder popular para la salud",
			"minsalud",
		],
		publishes: ["mpps-boletin"],
	},
	{
		id: "inst.mpp-defensa",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Defensa",
		en: "Ministry of Defence",
		organs: [`${MPP} PARA LA DEFENSA`],
		text: [
			"ministerio de la defensa",
			"ministerio de defensa",
			"ministerio del poder popular para la defensa",
		],
	},
	{
		id: "inst.mpp-relaciones-interiores",
		kind: "ministry",
		es: "Ministerio del Poder Popular para Relaciones Interiores, Justicia y Paz",
		en: "Ministry of the Interior, Justice and Peace",
		organs: [`${MPP} PARA RELACIONES INTERIORES, JUSTICIA Y PAZ`],
		text: [
			"ministerio de interior",
			"ministerio de relaciones interiores",
			"ministerio para relaciones interiores",
		],
	},
	{
		id: "inst.mpp-relaciones-exteriores",
		kind: "ministry",
		es: "Ministerio del Poder Popular para Relaciones Exteriores y Comercio Internacional",
		en: "Ministry of Foreign Affairs and International Trade",
		short: "Cancillería",
		aliases: ["Cancillería"],
		organs: [`${MPP} PARA RELACIONES EXTERIORES Y COMERCIO INTERNACIONAL`],
		text: ["cancilleria venezolana", "ministerio de relaciones exteriores"],
	},
	{
		id: "inst.mpp-economia-finanzas",
		kind: "ministry",
		es: "Ministerio del Poder Popular de Economía y Finanzas",
		en: "Ministry of Economy and Finance",
		organs: [`${MPP} DE ECONOMÍA Y FINANZAS`],
		text: ["ministerio de economia y finanzas"],
	},
	{
		id: "inst.mpp-energia-electrica",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Energía Eléctrica",
		en: "Ministry of Electric Power",
		organs: [`${MPP} PARA LA ENERGÍA ELÉCTRICA`],
		text: ["ministerio de energia electrica", "ministerio para la energia electrica"],
	},
	{
		id: "inst.mpp-atencion-aguas",
		kind: "ministry",
		es: "Ministerio del Poder Popular de Atención de las Aguas",
		en: "Ministry of Water Services",
		organs: [`${MPP} DE ATENCIÓN DE LAS AGUAS`],
		text: ["ministerio de atencion de las aguas"],
	},
	{
		id: "inst.mpp-transporte",
		kind: "ministry",
		es: "Ministerio del Poder Popular para el Transporte",
		en: "Ministry of Transport",
		organs: [`${MPP} PARA EL TRANSPORTE`],
		text: ["ministerio de transporte", "ministerio para el transporte"],
	},
	{
		id: "inst.mpp-educacion",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Educación",
		en: "Ministry of Education",
		organs: [`${MPP} PARA LA EDUCACIÓN`],
		text: ["ministerio de educacion", "ministerio para la educacion"],
	},
	{
		id: "inst.mpp-educacion-universitaria",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Educación Universitaria",
		en: "Ministry of University Education",
		organs: [`${MPP} PARA LA EDUCACIÓN UNIVERSITARIA`],
		text: ["ministerio de educacion universitaria"],
	},
	{
		id: "inst.mpp-ciencia-tecnologia",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Ciencia y Tecnología",
		en: "Ministry of Science and Technology",
		organs: [`${MPP} PARA LA CIENCIA Y TECNOLOGÍA`],
		text: ["ministerio de ciencia y tecnologia"],
	},
	{
		id: "inst.mpp-cultura",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Cultura",
		en: "Ministry of Culture",
		organs: [`${MPP} PARA LA CULTURA`],
		text: ["ministerio de cultura", "ministerio para la cultura"],
	},
	{
		id: "inst.mpp-turismo",
		kind: "ministry",
		es: "Ministerio del Poder Popular para el Turismo",
		en: "Ministry of Tourism",
		organs: [`${MPP} PARA EL TURISMO`],
		text: ["ministerio de turismo", "ministerio para el turismo"],
	},
	{
		id: "inst.mpp-habitat-vivienda",
		kind: "ministry",
		es: "Ministerio del Poder Popular para Hábitat y Vivienda",
		en: "Ministry of Habitat and Housing",
		organs: [`${MPP} PARA HÁBITAT Y VIVIENDA`],
		text: ["ministerio de habitat y vivienda"],
	},
	{
		id: "inst.mpp-ecosocialismo",
		kind: "ministry",
		es: "Ministerio del Poder Popular para el Ecosocialismo",
		en: "Ministry of Ecosocialism",
		organs: [`${MPP} PARA EL ECOSOCIALISMO`, `${MPP} PARA ECOSOCIALISMO`],
		text: ["ministerio de ecosocialismo", "ministerio para el ecosocialismo"],
	},
	{
		id: "inst.mpp-agricultura-productiva",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Agricultura Productiva y Tierras",
		en: "Ministry of Productive Agriculture and Land",
		organs: [`${MPP} PARA LA AGRICULTURA PRODUCTIVA Y TIERRAS`],
		text: ["ministerio de agricultura productiva"],
	},
	{
		id: "inst.mpp-pesca",
		kind: "ministry",
		es: "Ministerio del Poder Popular de Pesca y Acuicultura",
		en: "Ministry of Fisheries and Aquaculture",
		organs: [`${MPP} DE PESCA Y ACUICULTURA`],
		text: ["ministerio de pesca y acuicultura"],
	},
	{
		id: "inst.mpp-planificacion",
		kind: "ministry",
		es: "Ministerio del Poder Popular de Planificación",
		en: "Ministry of Planning",
		organs: [`${MPP} DE PLANIFICACIÓN`],
		text: ["ministerio de planificacion"],
	},
	{
		id: "inst.mpp-comunas",
		kind: "ministry",
		es: "Ministerio del Poder Popular para las Comunas, Movimientos Sociales y Agricultura Urbana",
		en: "Ministry of Communes, Social Movements and Urban Agriculture",
		organs: [`${MPP} PARA LAS COMUNAS, MOVIMIENTOS SOCIALES Y AGRICULTURA URBANA`],
		text: ["ministerio de las comunas", "ministerio para las comunas"],
	},
	{
		id: "inst.mpp-despacho-presidencia",
		kind: "ministry",
		es: "Ministerio del Poder Popular del Despacho de la Presidencia y Seguimiento de la Gestión de Gobierno",
		en: "Ministry of the Office of the Presidency",
		organs: [`${MPP} DEL DESPACHO DE LA PRESIDENCIA Y SEGUIMIENTO DE LA GESTIÓN DE GOBIERNO`],
		text: ["ministerio del despacho de la presidencia"],
	},
	{
		id: "inst.mpp-industrias-comercio",
		kind: "ministry",
		es: "Ministerio del Poder Popular de Industrias y Comercio Nacional",
		en: "Ministry of Industry and National Trade",
		organs: [`${MPP} DE INDUSTRIAS Y COMERCIO NACIONAL`],
		text: ["ministerio de industrias y comercio"],
	},
	{
		id: "inst.mpp-juventud",
		kind: "ministry",
		es: "Ministerio del Poder Popular para la Juventud",
		en: "Ministry of Youth",
		organs: [`${MPP} PARA LA JUVENTUD`],
		text: ["ministerio de la juventud", "ministerio para la juventud"],
	},
	{
		id: "inst.mpp-trabajo",
		kind: "ministry",
		es: "Ministerio del Poder Popular para el Proceso Social de Trabajo",
		en: "Ministry of Labour",
		organs: [`${MPP} PARA EL PROCESO SOCIAL DE TRABAJO`],
		text: ["ministerio del trabajo", "ministerio para el proceso social de trabajo"],
	},
	{
		id: "inst.mpp-deporte",
		kind: "ministry",
		es: "Ministerio del Poder Popular para el Deporte",
		en: "Ministry of Sport",
		organs: [`${MPP} PARA EL DEPORTE`],
		text: ["ministerio del deporte", "ministerio para el deporte"],
	},
	// ——— agencies and state companies ———
	{
		id: "inst.bcv",
		kind: "agency",
		es: "Banco Central de Venezuela",
		en: "Central Bank of Venezuela",
		short: "BCV",
		organs: ["BANCO CENTRAL DE VENEZUELA"],
		text: ["banco central de venezuela", "bcv"],
		homepage: "https://www.bcv.org.ve/",
		publishes: [
			"bcv-official",
			"bcv-history",
			"bcv-inpc",
			"bcv-api",
			"bcv-reserves",
			"bcv-liquidity",
			"bcv-intervention",
		],
	},
	{
		id: "inst.funvisis",
		kind: "agency",
		es: "Fundación Venezolana de Investigaciones Sismológicas",
		en: "Venezuelan Foundation for Seismological Research",
		short: "FUNVISIS",
		text: ["funvisis"],
		homepage: "http://www.funvisis.gob.ve/",
		attachedTo: "inst.mpp-ciencia-tecnologia",
		publishes: ["funvisis-quakes"],
	},
	{
		id: "inst.ine",
		kind: "agency",
		es: "Instituto Nacional de Estadística",
		en: "National Statistics Institute",
		short: "INE",
		text: ["instituto nacional de estadistica"],
		homepage: "http://www.ine.gob.ve/",
	},
	{
		id: "inst.seniat",
		kind: "agency",
		es: "Servicio Nacional Integrado de Administración Aduanera y Tributaria",
		en: "Tax and Customs Administration",
		short: "SENIAT",
		text: ["seniat"],
		homepage: "http://www.seniat.gob.ve/",
	},
	{
		id: "inst.saime",
		kind: "agency",
		es: "Servicio Administrativo de Identificación, Migración y Extranjería",
		en: "Identification, Migration and Immigration Service",
		short: "SAIME",
		text: ["saime"],
		homepage: "https://www.saime.gob.ve/",
	},
	{
		id: "inst.conatel",
		kind: "agency",
		es: "Comisión Nacional de Telecomunicaciones",
		en: "National Telecommunications Commission",
		short: "Conatel",
		text: ["conatel"],
		homepage: "http://www.conatel.gob.ve/",
	},
	{
		id: "inst.inac",
		kind: "agency",
		es: "Instituto Nacional de Aeronáutica Civil",
		en: "National Civil Aviation Institute",
		short: "INAC",
		text: ["inac", "instituto nacional de aeronautica civil"],
		homepage: "http://www.inac.gob.ve/",
		attachedTo: "inst.mpp-transporte",
	},
	{
		id: "inst.imprenta-nacional",
		kind: "agency",
		es: "Servicio Autónomo Imprenta Nacional y Gaceta Oficial",
		en: "National Printing Office and Official Gazette",
		aliases: ["Gaceta Oficial", "Imprenta Nacional"],
		homepage: "http://www.imprentanacional.gob.ve/",
		publishes: ["gaceta-oficial"],
	},
	{
		id: "inst.pdvsa",
		kind: "state-company",
		es: "Petróleos de Venezuela, S.A.",
		en: "Petróleos de Venezuela (state oil company)",
		short: "PDVSA",
		text: ["pdvsa", "petroleos de venezuela"],
		homepage: "http://www.pdvsa.com/",
	},
	{
		id: "inst.pequiven",
		kind: "state-company",
		es: "Petroquímica de Venezuela, S.A.",
		en: "Petroquímica de Venezuela (state petrochemical company)",
		short: "Pequiven",
		text: ["pequiven"],
		homepage: "http://www.pequiven.com/",
	},
	{
		id: "inst.corpoelec",
		kind: "state-company",
		es: "Corporación Eléctrica Nacional",
		en: "National Electric Corporation",
		short: "Corpoelec",
		text: ["corpoelec"],
		homepage: "http://www.corpoelec.gob.ve/",
		attachedTo: "inst.mpp-energia-electrica",
	},
	{
		id: "inst.cantv",
		kind: "state-company",
		es: "Compañía Anónima Nacional Teléfonos de Venezuela",
		en: "CANTV (state telephone company)",
		short: "CANTV",
		text: ["cantv"],
		homepage: "https://www.cantv.com.ve/",
	},
	{
		id: "inst.movilnet",
		kind: "state-company",
		es: "Telecomunicaciones Movilnet",
		en: "Movilnet (state mobile operator)",
		short: "Movilnet",
		text: ["movilnet"],
		homepage: "https://www.movilnet.com.ve/",
		attachedTo: "inst.cantv",
	},
	{
		id: "inst.hidroven",
		kind: "state-company",
		es: "Hidrológica de Venezuela",
		en: "Hidroven (state water company)",
		short: "Hidroven",
		text: ["hidroven"],
	},
	{
		id: "inst.hidrocapital",
		kind: "state-company",
		es: "Hidrológica de la Región Capital",
		en: "Hidrocapital (Caracas water company)",
		short: "Hidrocapital",
		text: ["hidrocapital"],
		attachedTo: "inst.hidroven",
	},
	{
		id: "inst.bolipuertos",
		kind: "state-company",
		es: "Bolivariana de Puertos, S.A.",
		en: "Bolipuertos (state port authority)",
		short: "Bolipuertos",
		text: ["bolipuertos"],
	},
	{
		id: "inst.conviasa",
		kind: "state-company",
		es: "Consorcio Venezolano de Industrias Aeronáuticas y Servicios Aéreos",
		en: "Conviasa (state airline)",
		short: "Conviasa",
		text: ["conviasa"],
	},
	// ——— state bodies on OFAC's Venezuela lists (added 2026-09-28; src/ontology/sanctions.ts links their entries) ———
	{
		id: "inst.pdv-holding",
		kind: "state-company",
		es: "PDV Holding, Inc. (filial de PDVSA en EE. UU.)",
		en: "PDV Holding, Inc. (PDVSA's US subsidiary)",
		short: "PDV Holding",
		text: ["pdv holding"],
		attachedTo: "inst.pdvsa",
	},
	{
		id: "inst.citgo",
		kind: "state-company",
		es: "CITGO Holding y CITGO Petroleum (filiales de PDVSA en EE. UU.)",
		en: "CITGO Holding and CITGO Petroleum (PDVSA's US subsidiaries)",
		short: "CITGO",
		text: ["citgo"],
		attachedTo: "inst.pdv-holding",
	},
	{
		id: "inst.cvg",
		kind: "state-company",
		es: "Corporación Venezolana de Guayana",
		en: "Venezuelan Guayana Corporation",
		short: "CVG",
		text: ["corporacion venezolana de guayana"],
	},
	{
		id: "inst.minerven",
		kind: "state-company",
		es: "CVG Compañía General de Minería de Venezuela (Minerven)",
		en: "Minerven (state gold mining company)",
		short: "Minerven",
		text: ["minerven"],
	},
	{
		id: "inst.banco-de-venezuela",
		kind: "state-company",
		es: "Banco de Venezuela, S.A. Banco Universal",
		en: "Banco de Venezuela (state-owned bank)",
		short: "Banco de Venezuela",
		text: ["banco de venezuela"],
	},
	{
		id: "inst.banco-bicentenario",
		kind: "state-company",
		es: "Banco Bicentenario del Pueblo",
		en: "Banco Bicentenario (state-owned bank)",
		short: "Banco Bicentenario",
		text: ["banco bicentenario"],
	},
	{
		id: "inst.bandes",
		kind: "agency",
		es: "Banco de Desarrollo Económico y Social de Venezuela",
		en: "Economic and Social Development Bank of Venezuela",
		short: "BANDES",
		text: ["bandes", "banco de desarrollo economico y social de venezuela"],
	},
	{
		id: "inst.inea",
		kind: "agency",
		es: "Instituto Nacional de los Espacios Acuáticos",
		en: "National Institute of Aquatic Spaces",
		short: "INEA",
		text: ["instituto nacional de los espacios acuaticos"],
	},
	// ——— security bodies (institutions only: never an individual craft or person) ———
	{
		id: "inst.fanb",
		kind: "security",
		es: "Fuerza Armada Nacional Bolivariana",
		en: "National Bolivarian Armed Forces",
		short: "FANB",
		text: ["fanb", "fuerza armada nacional bolivariana"],
		attachedTo: "inst.mpp-defensa",
	},
	{
		id: "inst.gnb",
		kind: "security",
		es: "Guardia Nacional Bolivariana",
		en: "Bolivarian National Guard",
		short: "GNB",
		text: ["gnb", "guardia nacional bolivariana"],
		attachedTo: "inst.fanb",
	},
	{
		id: "inst.pnb",
		kind: "security",
		es: "Policía Nacional Bolivariana",
		en: "Bolivarian National Police",
		short: "PNB",
		text: ["pnb", "policia nacional bolivariana"],
		attachedTo: "inst.mpp-relaciones-interiores",
	},
	{
		id: "inst.cicpc",
		kind: "security",
		es: "Cuerpo de Investigaciones Científicas, Penales y Criminalísticas",
		en: "Scientific, Criminal and Forensic Investigations Corps",
		short: "CICPC",
		text: ["cicpc"],
		attachedTo: "inst.mpp-relaciones-interiores",
	},
	{
		id: "inst.sebin",
		kind: "security",
		es: "Servicio Bolivariano de Inteligencia Nacional",
		en: "Bolivarian National Intelligence Service",
		short: "SEBIN",
		text: ["sebin"],
	},
	{
		id: "inst.dgcim",
		kind: "security",
		es: "Dirección General de Contrainteligencia Militar",
		en: "Directorate General of Military Counterintelligence",
		short: "DGCIM",
		text: ["dgcim"],
		attachedTo: "inst.mpp-defensa",
	},
];
