/**
 * The weekly MPPS job, one command (the maintainer runs it after each new bulletin is listed):
 *
 *   bun scripts/health/mpps-transcribe.ts [--dry-run] [--dir <folder for the PDFs>]   (default dir: runs/mpps)
 *
 * Reads the bulletin list, downloads the PDFs it does not have yet (the newest listed week included; one every 3 s,
 * project User-Agent), converts each to text with `pdftotext` (poppler) and reads it with readWeek(). Then prints
 * what changed against the committed src/adapters/mpps-boletin/weeks.gen.ts (weeks added or gone, every figure that
 * changed) and the newest week's figures, and writes the file unless --dry-run. A figure the patterns do not find is
 * null, never guessed; the person reviews the diff, runs `bun run check` and commits.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { diffWeeks, missingFigures, type Week, weekKey } from "../../src/adapters/mpps-boletin/diff.ts";
import { MPPS_LIST, parseList } from "../../src/adapters/mpps-boletin/index.ts";
import { readWeek } from "../../src/adapters/mpps-boletin/transcribe.ts";
import { WEEKS as COMMITTED } from "../../src/adapters/mpps-boletin/weeks.gen.ts";
import { USER_AGENT } from "../../src/core/http.ts";

const root = join(import.meta.dir, "..", "..");
const argDir = process.argv.indexOf("--dir");
const dir = argDir > 0 ? (process.argv[argDir + 1] ?? "") : join(root, "runs", "mpps");
const dryRun = process.argv.includes("--dry-run");
mkdirSync(dir, { recursive: true });

if (!Bun.which("pdftotext")) {
	console.error(
		"Falta pdftotext (poppler). Instálalo y repite:\n" +
			"  Arch: sudo pacman -S poppler · Debian/Ubuntu: sudo apt install poppler-utils · macOS: brew install poppler",
	);
	process.exit(1);
}

async function get(url: string): Promise<Response> {
	const res = await fetch(url, {
		headers: { "user-agent": USER_AGENT },
		signal: AbortSignal.timeout(120_000),
	});
	if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
	return res;
}

const html = await (await get(MPPS_LIST)).text();
writeFileSync(join(dir, "list.html"), html);
const entries = parseList(html);
const byWeek = new Map<string, (typeof entries)[number]>();
for (const e of entries) {
	const key = `${e.year}-${String(e.week).padStart(2, "0")}`;
	if (!byWeek.has(key)) byWeek.set(key, e);
}

const rows: (Week & { key: string })[] = [];
for (const [key, e] of [...byWeek.entries()].sort(([a], [b]) => a.localeCompare(b))) {
	const pdf = join(dir, basename(new URL(e.pdfUrl).pathname));
	if (!existsSync(pdf)) {
		console.error(`descargando ${e.pdfUrl}`);
		writeFileSync(pdf, Buffer.from(await (await get(e.pdfUrl)).arrayBuffer()));
		await Bun.sleep(3_000);
	}
	const txt = pdf.replace(/\.pdf$/, ".raw.txt");
	if (!existsSync(txt)) {
		const run = Bun.spawnSync(["pdftotext", pdf, txt]);
		if (run.exitCode !== 0) throw new Error(`pdftotext ${pdf}: ${run.stderr.toString()}`);
	}
	const figures = readWeek(readFileSync(txt, "utf8"), e.week);
	rows.push({ key, year: e.year, week: e.week, pdfUrl: e.pdfUrl, ...figures });
}

const newest = rows.at(-1);
if (!newest) {
	console.error("La lista no trae ningún boletín: ¿cambió la página? Nada escrito.");
	process.exit(1);
}
const diff = diffWeeks(
	COMMITTED,
	rows.map(({ key: _, ...w }) => w),
);
console.log(`\nBoletín más reciente en la lista: ${weekKey(newest)} (${newest.pdfUrl})`);
console.table([newest].map(({ pdfUrl: _, key: __, ...r }) => r));
const gaps = missingFigures(newest);
if (gaps.length)
	console.log(
		`Sin cifra en ${weekKey(newest)} (revisa el PDF o el patrón en transcribe.ts): ${gaps.join(", ")}`,
	);
console.log("\nCambios frente a weeks.gen.ts:");
for (const w of diff.added) console.log(`  + ${weekKey(w)} nueva`);
for (const w of diff.removed) console.log(`  - ${weekKey(w)} ya no está en la lista`);
for (const c of diff.changed) console.log(`  ~ ${c.key} ${c.field}: ${c.from} → ${c.to}`);
if (!diff.added.length && !diff.removed.length && !diff.changed.length) {
	console.log("  ninguno: weeks.gen.ts ya está al día. Nada escrito.");
	process.exit(0);
}
if (dryRun) {
	console.log("\n--dry-run: nada escrito.");
	process.exit(0);
}

const body = `// Generated by scripts/health/mpps-transcribe.ts from the MPPS bulletins (PDF → pdftotext → readWeek). Do not
// edit by hand: fix the pattern in transcribe.ts and regenerate. Each row's source is its PDF (pdfUrl).
import type { WeekFigures } from "./transcribe.ts";

export type TranscribedWeek = WeekFigures & {
	readonly year: number;
	readonly week: number;
	readonly pdfUrl: string;
};

/** Transcribed ${new Date().toISOString().slice(0, 10)}. */
export const TRANSCRIBED_AT = "${new Date().toISOString().slice(0, 10)}";

export const WEEKS: readonly TranscribedWeek[] = ${JSON.stringify(
	rows.map(({ key: _, ...r }) => r),
	null,
	"\t",
)};
`;
const out = join(root, "src", "adapters", "mpps-boletin", "weeks.gen.ts");
writeFileSync(out, body);
Bun.spawnSync(["bunx", "biome", "format", "--write", out], { cwd: root });
console.log(`\n${rows.length} semanas → ${out}\nRevisa \`git diff\`, corre \`bun run check\` y haz commit.`);
