/**
 * Transcribes the national figures of the MPPS weekly epidemiological bulletins into
 * src/adapters/mpps-boletin/weeks.gen.ts (development time only; needs `pdftotext` from poppler).
 *
 *   bun scripts/health/mpps-transcribe.ts [--dir <folder for the PDFs>]   (default: runs/mpps)
 *
 * Reads the bulletin list, downloads the PDFs it does not have yet (one every 3 s, project User-Agent) into the
 * bulk-data directory, converts each to text and reads it with readWeek(). Prints every week's figures and the
 * checks that failed, so a person reviews the diff before committing it. A figure the patterns do not find is null.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { MPPS_LIST, parseList } from "../../src/adapters/mpps-boletin/index.ts";
import { readWeek } from "../../src/adapters/mpps-boletin/transcribe.ts";
import { USER_AGENT } from "../../src/core/http.ts";

const root = join(import.meta.dir, "..", "..");
const argDir = process.argv.indexOf("--dir");
const dir = argDir > 0 ? (process.argv[argDir + 1] ?? "") : join(root, "runs", "mpps");
mkdirSync(dir, { recursive: true });

async function get(url: string): Promise<Response> {
	const res = await fetch(url, {
		headers: { "user-agent": USER_AGENT },
		signal: AbortSignal.timeout(120_000),
	});
	if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
	return res;
}

const html = await (await get(MPPS_LIST)).text();
writeFileSync(join(dir, "list.html"), html);
const entries = parseList(html);
const byWeek = new Map<string, (typeof entries)[number]>();
for (const e of entries) {
	const key = `${e.year}-${String(e.week).padStart(2, "0")}`;
	if (!byWeek.has(key)) byWeek.set(key, e);
}

const rows = [];
for (const [key, e] of [...byWeek.entries()].sort(([a], [b]) => a.localeCompare(b))) {
	const pdf = join(dir, basename(new URL(e.pdfUrl).pathname));
	if (!existsSync(pdf)) {
		console.error(`descargando ${e.pdfUrl}`);
		writeFileSync(pdf, Buffer.from(await (await get(e.pdfUrl)).arrayBuffer()));
		await Bun.sleep(3_000);
	}
	const txt = pdf.replace(/\.pdf$/, ".raw.txt");
	if (!existsSync(txt)) {
		const run = Bun.spawnSync(["pdftotext", pdf, txt]);
		if (run.exitCode !== 0) throw new Error(`pdftotext ${pdf}: ${run.stderr.toString()}`);
	}
	const figures = readWeek(readFileSync(txt, "utf8"), e.week);
	rows.push({ key, year: e.year, week: e.week, pdfUrl: e.pdfUrl, ...figures });
}

console.table(rows.map(({ pdfUrl: _, ...r }) => r));

const body = `// Generated by scripts/health/mpps-transcribe.ts from the MPPS bulletins (PDF → pdftotext → readWeek). Do not
// edit by hand: fix the pattern in transcribe.ts and regenerate. Each row's source is its PDF (pdfUrl).
import type { WeekFigures } from "./transcribe.ts";

export type TranscribedWeek = WeekFigures & {
	readonly year: number;
	readonly week: number;
	readonly pdfUrl: string;
};

/** Transcribed ${new Date().toISOString().slice(0, 10)}. */
export const TRANSCRIBED_AT = "${new Date().toISOString().slice(0, 10)}";

export const WEEKS: readonly TranscribedWeek[] = ${JSON.stringify(
	rows.map(({ key: _, ...r }) => r),
	null,
	"\t",
)};
`;
const out = join(root, "src", "adapters", "mpps-boletin", "weeks.gen.ts");
writeFileSync(out, body);
Bun.spawnSync(["bunx", "biome", "format", "--write", out], { cwd: root });
console.error(`${rows.length} semanas → ${out}`);
