import type { FeedHealth } from "../../core/health.ts";
import type { Adapter, Json } from "../../core/types.ts";
import type { ChainEntry } from "../../intel/chain.ts";
import { h, page, safeHref } from "./shell.ts";

/**
 * GET /informe: the daily report on paper. The code-built brief (figures with source and time, the most-covered
 * stories), active incidents, the state of every feed and the licence of every source, laid out for A4/Letter
 * printing; the browser's "Print → Save as PDF" makes the PDF. No script, nothing generated by a model except a
 * written brief the user chose to produce, which is labelled as AI text.
 */

interface BriefFigure {
	label: string;
	value: string;
	source: string;
	observedAt: number | null;
	url: string | null;
	stale?: boolean;
}
interface BriefStory {
	title: string;
	url: string;
	outlets: string[];
	at: number;
	state: string | null;
}
interface BriefView {
	day: string;
	generatedAt: number;
	figures: BriefFigure[];
	stories: BriefStory[];
	method: string;
}
interface Written {
	model: string;
	text: string;
	at: number;
	dataAt: number;
	sources: string[];
}
interface IncidentLite {
	id: string;
	title: { es: string };
	stateName: string | null;
	status: string;
	startAt: number;
	lastEvidenceAt: number;
	evidenceTotal: number;
	strength: { es: string };
	reportsOnly: boolean;
}

const CARACAS = new Intl.DateTimeFormat("es-VE", {
	timeZone: "America/Caracas",
	day: "numeric",
	month: "short",
	year: "numeric",
	hour: "2-digit",
	minute: "2-digit",
	hourCycle: "h23",
});

/** "24 sept 2026, 14:05" in Caracas time. */
export function caracas(t: number | null | undefined): string {
	return typeof t === "number" && Number.isFinite(t) ? CARACAS.format(new Date(t)) : "—";
}

const STATE_ES: Record<FeedHealth["state"], string> = {
	ok: "al día",
	stale: "atrasada",
	degraded: "con fallos",
	failing: "caída",
	locked: "sin clave",
	off: "apagada",
	pending: "sin lecturas",
};

function age(ms: number | null): string {
	if (ms === null) return "—";
	const m = Math.round(ms / 60_000);
	if (m < 60) return `${m} min`;
	const hrs = Math.round(m / 60);
	return hrs < 48 ? `${hrs} h` : `${Math.round(hrs / 24)} d`;
}

interface SectionAge {
	/** At least one of the section's feeds is live (ok or degraded). */
	live: boolean;
	/** The newest good read among its feeds. */
	lastAt: number | null;
	now: number;
}

/** The freshness of a section's inputs, by the same rule as the page: current while any of its feeds is live. */
export function sectionAge(
	feeds: readonly string[],
	health: ReadonlyMap<string, FeedHealth>,
	now: number,
): SectionAge {
	const rows = feeds
		.map((id) => health.get(id))
		.filter((f): f is FeedHealth => f !== undefined && f.state !== "off" && f.state !== "locked");
	const live = rows.some((f) => f.state === "ok" || f.state === "degraded");
	const lastAt = Math.max(0, ...rows.map((f) => f.lastSuccessAt ?? 0)) || null;
	return { live, lastAt, now };
}

/** "Calculado 25 sept 2026, 02:50. Señales medidas leídas por última vez hace 5 h (atrasadas)." */
function ageNote(a: SectionAge, computedAt: number | null, what: string): string {
	const cap = what.charAt(0).toUpperCase() + what.slice(1);
	const read =
		a.lastAt === null
			? `Sin ${what} leídas todavía`
			: `${cap} leídas por última vez hace ${age(a.now - a.lastAt)}`;
	const late = a.lastAt !== null && !a.live ? ' <span class="tag tag--stale">atrasadas</span>' : "";
	return `<p class="note age">${computedAt ? `Calculado <time>${h(caracas(computedAt))}</time>. ` : ""}${h(read)}${late}.</p>`;
}

function link(url: string | null | undefined, text: string): string {
	const href = safeHref(url);
	return href ? `<a href="${h(href)}">${h(text)}</a>` : h(text);
}

export function reportPage(input: {
	readonly now: number;
	readonly version: string;
	readonly origin: string;
	readonly brief: Json | undefined;
	readonly ai: Json | undefined;
	readonly incidents: Json | undefined;
	readonly health: readonly FeedHealth[];
	readonly adapters: readonly Adapter[];
	/** The feeds the report's figures come from (the brief's and the incidents' sources). */
	readonly usedFeeds: readonly string[];
	readonly chainHead: ChainEntry | null;
}): string {
	const brief = input.brief as unknown as BriefView | undefined;
	const written =
		(input.ai as unknown as { writtenBrief?: Written | null } | undefined)?.writtenBrief ?? null;
	const incView = input.incidents as unknown as
		| { asOf?: number; incidents?: IncidentLite[]; feeds?: string[] }
		| undefined;
	const incidents = (incView?.incidents ?? []).filter((i) => i.status === "active");
	const byId = new Map(input.adapters.map((a) => [a.id, a]));
	const healthById = new Map(input.health.map((f) => [f.id, f]));
	// Each section says how old its inputs are; a claim of absence on inputs none of which is live is not made
	// (review 4, M2: "Ningún incidente activo" printed on 5-hour-old signals).
	const incidentsAge = sectionAge(incView?.feeds ?? [], healthById, input.now);
	const newsAge = sectionAge(
		input.adapters.filter((a) => a.layer === "news").map((a) => a.id),
		healthById,
		input.now,
	);

	const figures = brief
		? `<div class="scroll" tabindex="0" role="region" aria-label="Cifras"><table class="figures"><caption class="sr">Cifras del día</caption>
<thead><tr><th scope="col">Cifra</th><th scope="col">Valor</th><th scope="col">Fuente</th><th scope="col">Hora del dato</th></tr></thead>
<tbody>${brief.figures
				.map(
					(f) =>
						`<tr><th scope="row">${h(f.label)}</th><td>${h(f.value)}${f.stale ? ' <span class="tag tag--stale">dato atrasado</span>' : ""}</td><td>${link(f.url, f.source)}</td><td><time>${h(caracas(f.observedAt))}</time></td></tr>`,
				)
				.join("")}</tbody></table></div>`
		: "<p>El resumen no está disponible ahora.</p>";

	const stories = brief?.stories.length
		? `<ol class="stories">${brief.stories
				.map(
					(s) =>
						`<li>${link(s.url, s.title)}<br><span class="note">${s.state ? `${h(s.state)} · ` : ""}${s.outlets.length} ${s.outlets.length === 1 ? "medio" : "medios"}: ${h(s.outlets.join(", "))} · <time>${h(caracas(s.at))}</time></span></li>`,
				)
				.join("")}</ol>`
		: "<p>Sin historias con varios medios en las últimas 24 horas.</p>";

	const ai = written
		? `<section class="ai" aria-labelledby="ia"><h2 id="ia">Resumen escrito por IA (${h(written.model)})</h2>
<p class="warning"><strong>Texto de IA, no un hecho.</strong> Escrito ${h(caracas(written.at))} con los datos de ${h(caracas(written.dataAt))}. Puede resumir mal u omitir algo; las cifras de arriba son las que valen.</p>
<p>${h(written.text)}</p></section>`
		: "";

	const incidentList = incidents.length
		? `<div class="scroll" tabindex="0" role="region" aria-label="Incidentes activos"><table><thead><tr><th scope="col">Incidente</th><th scope="col">Desde</th><th scope="col">Última evidencia</th><th scope="col">Solidez</th></tr></thead><tbody>${incidents
				.map(
					(i) =>
						`<tr><th scope="row">${h(i.title.es)}</th><td><time>${h(caracas(i.startAt))}</time></td><td><time>${h(caracas(i.lastEvidenceAt))}</time></td><td>${h(i.strength.es)}; ${i.evidenceTotal} ${i.evidenceTotal === 1 ? "evidencia" : "evidencias"}${i.reportsOnly ? " (solo prensa)" : ""}</td></tr>`,
				)
				.join("")}</tbody></table></div>`
		: incidentsAge.live
			? "<p>Ningún incidente activo: ninguna combinación de señales independientes cumplió las reglas.</p>"
			: "<p>Sin datos recientes para afirmar que no hay incidentes: ninguna de sus fuentes medidas está al día.</p>";

	const counts = new Map<string, number>();
	for (const f of input.health) counts.set(f.state, (counts.get(f.state) ?? 0) + 1);
	// The table names only the late feeds this report's figures come from; the sentence counts all of them.
	const usedSet = new Set(input.usedFeeds);
	const allLate = input.health.filter(
		(f) => f.state === "stale" || f.state === "failing" || f.state === "degraded",
	);
	const late = allLate.filter((f) => usedSet.has(f.id) && byId.get(f.id)?.layer !== "news");
	const healthText = `${counts.get("ok") ?? 0} de ${input.health.filter((f) => f.state !== "off" && f.state !== "locked").length} fuentes activas al día${allLate.length ? `; con retraso o fallos: ${allLate.length} (lista completa en /estado)` : ""}.${late.length ? " Las de las cifras de este informe:" : ""}`;
	const lateTable = late.length
		? `<div class="scroll" tabindex="0" role="region" aria-label="Fuentes con retraso"><table><thead><tr><th scope="col">Fuente</th><th scope="col">Estado</th><th scope="col">Última lectura</th><th scope="col">Dato más reciente</th></tr></thead><tbody>${late
				.map((f) => {
					const a = byId.get(f.id);
					return `<tr><th scope="row">${h(a?.name.es ?? f.id)}</th><td>${h(STATE_ES[f.state])}</td><td>hace ${h(age(f.fetchAgeMs))}</td><td>hace ${h(age(f.dataAgeMs))}</td></tr>`;
				})
				.join("")}</tbody></table></div>`
		: "";

	const usedAll = input.usedFeeds.map((id) => byId.get(id)).filter((a): a is Adapter => a !== undefined);
	// News outlets (dozens, one licence each: titles and links only) collapse into one row.
	const used = usedAll.filter((a) => a.layer !== "news");
	const outlets = usedAll.filter((a) => a.layer === "news");
	const sources = `<div class="scroll" tabindex="0" role="region" aria-label="Fuentes y licencias"><table class="sources"><thead><tr><th scope="col">Fuente</th><th scope="col">Publica</th><th scope="col">Licencia</th><th scope="col">Atribución</th></tr></thead><tbody>${used
		.map(
			(a) =>
				`<tr><th scope="row">${link(a.homepage, a.name.es)}</th><td>${h(a.provider)}</td><td>${link(a.licence.url, a.licence.name)}</td><td>${h(a.licence.attribution)}</td></tr>`,
		)
		.join("")}${
		outlets.length
			? `<tr><th scope="row">Medios de noticias (${outlets.length})</th><td>${h(outlets.map((a) => a.name.es).join(", "))}</td><td>Titulares y enlaces; el texto es de cada medio</td><td>Cada titular enlaza a su medio</td></tr>`
			: ""
	}</tbody></table></div>`;

	const day = brief?.day ?? new Date(input.now).toISOString().slice(0, 10);
	const body = `<header class="head">
<p class="kicker">Vigía · Informe diario</p>
<h1>Venezuela, ${h(day)}</h1>
<p class="lede">Generado <time datetime="${new Date(input.now).toISOString()}">${h(caracas(input.now))}</time> (hora de Caracas; ${h(new Date(input.now).toISOString().slice(0, 16).replace("T", " "))} UTC) por Vigía ${h(input.version)}. Cada cifra lleva su fuente y la hora en que la fuente dice que es cierta.</p>
<p class="noprint note">Para guardarlo como PDF: Imprimir (Ctrl+P o ⌘P; en el teléfono, Compartir → Imprimir) y elija «Guardar como PDF». Datos en tabla: <a href="/api/v1/figures?format=csv">todas las cifras en CSV</a> · <a href="/api">API</a> · <a href="/resumen">volver al resumen</a></p>
</header>
<h2>Cifras</h2>
${brief ? `<p class="note age">Calculadas <time>${h(caracas(brief.generatedAt))}</time>; cada fila lleva la hora de su dato.</p>` : ""}
${figures}
<p class="note">${h(brief?.method ?? "")}</p>
${ai}
<h2>Incidentes activos</h2>
${ageNote(incidentsAge, incView?.asOf ?? null, "señales medidas")}
${incidentList}
<h2>Lo más cubierto en 24 horas</h2>
${ageNote(newsAge, brief?.generatedAt ?? null, "noticias")}
${stories}
<h2>Estado de las fuentes</h2>
<p>${h(healthText)}</p>
${lateTable}
<h2>Fuentes y licencias</h2>
${sources}
<h2>Verificación</h2>
<p class="note">${
		input.chainHead
			? `Archivo sellado hasta el día ${h(input.chainHead.day)} (UTC); cabeza de la cadena SHA-256: <code>${h(input.chainHead.digest)}</code>. Compruébelo en el equipo que generó este informe con <code>vigia verify</code>.`
			: "El archivo de este equipo todavía no tiene días sellados."
	} Lista completa de fuentes: ${h(input.origin)}/api/v1/sources</p>`;

	return page({
		title: `Informe de Vigía, ${day}`,
		lang: "es",
		description:
			"Informe diario de Vigía para imprimir: cifras con fuente y hora, incidentes, estado de las fuentes y licencias.",
		body,
		css: REPORT_CSS,
	});
}

const REPORT_CSS = `
.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}
.figures th[scope=row]{font-weight:600;color:var(--text)}
.stories li{margin:.4rem 0}
.warning{border-left:3px solid var(--warn);padding-left:8px}
@page{size:A4;margin:14mm 14mm 16mm}
@media print{
:root{--bg:#fff;--surface:#fff;--surface-2:#f2f2f2;--line:#ccc;--text:#000;--text-2:#333;--text-3:#444;--signal:#000;--info:#000;--warn:#000}
body{font-size:10.5pt;background:#fff;color:#000}
main{max-width:none;padding:0}
.noprint,.skip{display:none}
a{color:#000;text-decoration:none}
.sources a[href]::after{content:" (" attr(href) ")";font-size:8pt;color:#333;overflow-wrap:anywhere}
h2{break-after:avoid;page-break-after:avoid}
tr,li{break-inside:avoid;page-break-inside:avoid}
.scroll{overflow:visible}
.tag--stale{border-color:#000;color:#000}
}`;
